### ISSUE TITLE
Add feature autodetect prefered lenguage

### ISSUE THREAD

**Issue by codedeep** [rappasoft/laravel-boilerplate#1243]
I think it would be a good idea to implement the language autodetection and the time zone. 
so that if you can not determine it, put one by default or you can even deactivate the system of autodetection language. .env is good location locate=auto

Other idea is can set prefered language in setting of user profile

Interesting links on the subject:

https://stackoverflow.com/questions/36986236/how-to-detect-language-preference-in-laravel-5

https://stackoverflow.com/questions/49616638/laravel-localization-country-currency-language-timezone

https://glutendesign.com/posts/detect-and-change-language-on-the-fly-with-laravel

**Comment by rappasoft** [comment]
Feel free to make a PR
