### ISSUE TITLE
Vue Single Page Application (SPA) Backend

### ISSUE THREAD

**Issue by sam-ngu** [rappasoft/laravel-boilerplate#1246]
In one of my recent personal projects, I have developed an alternate Vue SPA backend where it can be toggled on/off via an env variable.

The backend UI is built using [Vuetify](https://vuetifyjs.com/en/) and has the same functionality as the current backend. Plus it supports dark mode :sunglasses: . 

Let me know what do you guys think. I'm happy to submit a PR for review :smile: 
![admin_dashboard](https://user-images.githubusercontent.com/30950704/59737358-ea46d500-928f-11e9-903c-5ae3f8dcbe5a.png)
![admin2](https://user-images.githubusercontent.com/30950704/59737359-eadf6b80-928f-11e9-93f3-4ae78bc2f7a2.png)

**Comment by netwrkx** [comment]
Cool..
Is it available in github?
I love to try it

**Comment by sam-ngu** [comment]
@netwrkx  yes sure, it's [here](https://github.com/sam-ngu/laravel-5-boilerplate)
Checkout the develop branch. However, it is not fully tested though. I will add more tests soon.
I use laradock, so if you want to use docker, you might want to configure it before proceeding.
