### ISSUE TITLE
Fresh Install login errors - data missing

### ISSUE THREAD

**Issue by NickGiacopuzzi** [rappasoft/laravel-boilerplate#1250]
InvalidArgumentException
Data missing

`/app/Listeners/Frontend/Auth/UserEventListener.php
<?php
 
namespace App\Listeners\Frontend\Auth;
 
/**
 * Class UserEventListener.
 */
class UserEventListener
{
    /**
     * @param $event
     */
    public function onLoggedIn($event)
    {
        $ip_address = request()->getClientIp();
 
        // Update the logging in users time & IP
        $event->user->fill([
            'last_login_at' => now()->toDateTimeString(),
            'last_login_ip' => $ip_address,
        ]);
 
        // Update the timezone via IP address
        $geoip = geoip($ip_address);
 
        if ($event->user->timezone !== $geoip['timezone']) {
            // Update the users timezone
            $event->user->fill([
                'timezone' => $geoip['timezone'],
            ]);
        }
 
        $event->user->save();
 
        \Log::info('User Logged In: '.$event->user->full_name);
    }
 
    /**
     * @param $event
     */
Arguments
array:2 [▼
  "last_login_at" => "2019-06-27 18:20:48"
  "last_login_ip" => "10.10.20.78"
]`

**Comment by NickGiacopuzzi** [comment]
Data missing {"userId":1,"exception":"[object] (InvalidArgumentException(code: 0): Data missing at /usr/share/nginx/html/agentsystem/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:537)

**Comment by NickGiacopuzzi** [comment]
Will also note that all PHPUnit tests pass, which is even more interesting. 

This is a fresh install on a CentOS production server (currently running an older version of Boiler just fine). Same thing happening on my local Homestead box as well, also a fresh install.

**Comment by Zugmaschine** [comment]
Is that Proplem solved?

**Comment by NickGiacopuzzi** [comment]
Not that I've seen. Havent checked git recently. I just ended up using an
earlier version.

**Comment by Zugmaschine** [comment]
Thanks for your answer. Why noone of the creators of this boilerplate answer to that proplem?
Thats not optimal ...

**Comment by Zugmaschine** [comment]
Thanks for your answer Nick. Why noone of the creators of this boilerplate answer to that proplem?
Thats not optimal ...
What version do you use?

**Comment by rappasoft** [comment]
Can not recreate. The only thing I can think of is Carbon is for some reason having trouble with the now() function.
