### ISSUE TITLE
Lodash dependency need to be  upgraded 

### ISSUE THREAD

**Issue by jaynarayan89** [rappasoft/laravel-boilerplate#1255]
--->boilerplate version 5.8
-->system info:
Linux jay-pc 5.0.0-21-generic #22-Ubuntu SMP Tue Jul 2 13:27:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Got the following warning  after  running `npm install`

added 1315 packages from 726 contributors and audited 901076 packages in 77.907s
**found 215 high severity vulnerabilities**
  run `npm audit fix` to fix them, or `npm audit` for details

As  suggested solution I did `npm audit fix` 
output:-

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ lodash@4.17.15
updated 1 package in 18.07s
fixed 215 of 215 vulnerabilities in 901076 scanned packages

**Comment by rappasoft** [comment]
Awaiting merge.
