### ISSUE TITLE
How Add Multiple Permission 

### ISSUE THREAD

**Issue by Vaibhavi111** [rappasoft/laravel-boilerplate#1256]
https://github.com/spatie/laravel-permission

**Comment by remluben** [comment]
Hello,

I am quite new to Laravel Boilerplate, so I hope my answer helps: 

1. You can find the detailed docs for spatie/laravel-permissions on their site unser https://docs.spatie.be/laravel-permission/v2/introduction/

2. The Laravel Boilerplate does not Provider the function to create permissions in the admin panel (*Backend*) but you can add Thema in the Database table by hand or via database seed - it will be available in the role management afterwards.

Kind regards,
Benjamin

**Comment by lerg96** [comment]
If you add a permission by hand in the database table you have to read carefully the docs, because you need to clean the cache to see this permission in your app.
