### ISSUE TITLE
Facebook/Google Login Unknown column 'api_token'

### ISSUE THREAD

**Issue by perffy** [rappasoft/laravel-boilerplate#1257]
Hi guys,

i have installed the last Laravel Boilerplate and have tried the Google Login, it was working fine. I was not able to run the Facebook login, because the domain doesn't had SSL, but I thought with SSL it will work too.

Than I have started making changes on my application and almost at the end i have tried again the Facebook/Google login with a new domain, these time with SSL.

Unfortunately this time I have received from both social networks the following error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'api_token' in 'where clause' (SQL: select * from `users` where `api_token` = signals and `users`.`deleted_at` is null limit 1)

I can see there is a new user, but I am not able to login. I have searched the whole project for the string 'api_token', but I am not able to find out where is coming that from.

Does anybody knows how to fix that ?

**Comment by Shuyinsama** [comment]
If it used to work then something must’ve changed it.

I assume and expected facebook to work locally without SSL too since i’ve done so on multiple occasions.

Do you have more of a error log? Maybe a stacktrace?
It seems to look for a api_token in the database but without knowing anything more specific searching for it is impossible

**Comment by rappasoft** [comment]
I'll be honest it's hard to keep up with the socialite changes and all the providers, so there's a good chance something changed. Since I don't have tests for each provider I can run.

**Comment by perffy** [comment]
The plugin is working, but from time to time this problem appears and i don't get it why.
On my webserver it was working brilliant and suddenly without any linked code changes, the error came again. But on my local computer it was still working. I have removed the entire code from the webserver and uploaded the same code again, but the error doesn't disappear. So i decided to add manual the column "api_token" to the users table and now everything is working :)
