### ISSUE TITLE
Spatie\Permission\Exceptions\RoleDoesNotExist There is no role named `user`.

### ISSUE THREAD

**Issue by naknode** [rappasoft/laravel-boilerplate#1275]
# Before you create an issue make sure that:
- Your issue is **strictly related to the boilerplate** itself. Questions about Laravel in general belongs to the [laravel](http://laravel.io/forum) or [laracasts](https://laracasts.com/discuss/) forums.
- You have read the [documentation](http://laravel-boilerplate.com) thoroughly.
- You have searched for a similar issues among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.

# Be explicit

Follow "Getting Started" instructions.
Run `php artisan migrate`
Register a user. Hit submit.

Error appears: "Spatie\Permission\Exceptions\RoleDoesNotExist There is no role named `user`."

# What version?

Latest as of now

**Comment by poseso** [comment]
What are your steps to reproduce the error ? I have installed a fresh version and everything is working ok

**Comment by naknode** [comment]
1. git clone
2. npm i
3. composer install
4. npm run dev
5. go to url via laravel valet
6. fill out register form
7. hit submit
8. error appears

**Comment by lukecurtis93** [comment]
sounds like you didn't run `php artisan migrate:fresh --seed` on your install.

**Comment by naknode** [comment]
@lukecurtis93 I was missing that command. Thanks.
