### ISSUE TITLE
Command "tinker" is not defined.

### ISSUE THREAD

**Issue by lerg96** [rappasoft/laravel-boilerplate#1276]
when I try to run tinker I receive the following error
`Command "tinker" is not defined.`
looking for I found a package missing in the composer.json
`"laravel/tinker": "^1.0"`
In the original [composer.json](https://github.com/laravel/laravel/blob/51a1297a2486e2b68883bba9e534ec903f0c10d4/composer.json#L14) this package is found, but not in this repository. Is it a bug or a feature?

**Comment by bzy39** [comment]
its feature, removed along laravel dump server and  laravel self-diagnosis. check changelog to see what changed..

**Comment by rappasoft** [comment]
It might come back as a side effect of adding a feature in the next release.
