### ISSUE TITLE
Upgrading from 5.7 to 6

### ISSUE THREAD

**Issue by abdosaeedelhassan** [rappasoft/laravel-boilerplate#1279]
i have old project with 5.7 i want to upgrade it to 6, is there any structure to do that, i tried more time but all are failed, conflict with composer packages or errors in npm run dev, i need help please.

**Comment by bryanrscott** [comment]
Hi, I have done this a few times.   I start with a off the shelf boilerplate install.  Then for each package I use do a reinstall (eg composer require laravel/tinker) to pickup the latest version for laravel 6.   I do wait until until all my dependencies are supported under laravel 6, which should pretty much be the case for a supported package.    If they are not updated yet, you might want to either assist in getting updated, or find another package.

 Then I step through copying sections from the previous version to the next making sure it all works at each step.
I start with the migrations, then the models, then seeds, then the repositories.  etc.

Note occasionally the boilerplate changes something that means you need to update you code as well.  This might not be explicitly documented but fortunately there are generally enough examples to work with.  For example in the update from 5.8 to 6.0 the way you define a repository model changed from 
    public function model() {
        return Model::class;
    }
to 
    public function __construct(Model $model) {
        $this->model = $model;
    }


https://github.com/rappasoft/laravel-boilerplate/releases

**Comment by abdosaeedelhassan** [comment]
thank you, i will do it
