### ISSUE TITLE
timezone support

### ISSUE THREAD

**Issue by bentran** [rappasoft/laravel-boilerplate#1292]
Using the latest version (6.x) of the boilerplate

I can see that there were previous discussions on timezone support. However cannot seem to find any indication of it being completed?

I need to support for displaying localised date/time base on the user's chosen timezone. How to best achieve this with whats currently available. I am setting UTC on the .env file. Just need to be able to display it correctly.

Thank you.

**Comment by bentran** [comment]
Looking at this further it seems boilerplate already store the timezone in the DB. I just can't work out how to allow setting the timezone from the backend gui and if the time that gets displayed is already factor in the timezone?

Thanks.

**Comment by lukecurtis93** [comment]
use carbon timezone to offset it, maybe in an accessor e.g.
```php
public function getLocalAppointmentTimeAttribute()
    {
        $appointmentTime = \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $this->appointment_time, 'UTC');
        $appointmentTime->tz = $this->calendar->timezone; //here you would set it to the logged in users timezone maybe

        return $appointmentTime->format('Y-m-d H:i:s');
    }
```

**Comment by bentran** [comment]
I had a look further and noticed that in some places like the profiles the times are already display localised https://github.com/rappasoft/laravel-boilerplate/search?q=convertToLocal&unscoped_q=convertToLocal

Looks like that needs to be done for all the other places where time are displayed / saved
