### ISSUE TITLE
Question on roles

### ISSUE THREAD

**Issue by asantisan** [rappasoft/laravel-boilerplate#1293]
OTB i have the administrator role. I'm allowing users to access the admin and i want to create there some routes for users with a specific role. How can i do this?

Laravel 6
6.0.1

**Comment by bryanrscott** [comment]
Does not sound great?   If your allowing users to access the administrator role, then they can grant themselves any other role they want?

But you could limit using the hasRole check.
Eg In the request class for your pages/section (App\Http\Requests\Backend)

    public function authorize()
    {
        return $this->user()->hasRole('your-role');
    }

**Comment by asantisan** [comment]
Yes it does. It's a great boilerplate, however, i'm finding a little bit confusing the routes creation.
As an example, i have a section for users (that can view backend) called "clients". Basically is for users to create their own clients inside the admin. Users have the assigned role of "clients"
The Client controllers are under the Auth folder:

`app/Http/Controllers/Backend/Auth/Client/ClientController.php`

```
public function index(ManageClientRequest $request)
    {

        return view('backend.auth.client.index')
            ->withClients($this->clientRepository->getActivePaginated(5, 'id', 'asc'));

    }
```

`app/Models/Auth/Client.php`

```
...

class Client extends Model
{
    public function user(){
        return $this->belongsTo('App\Models\User');
    }
}
```

What i'm trying to figure out is where the route/s should go? Curretly this is what i have in the auth route file:

`
routes/backend/auth.php
`

```
      ...// Ends Role Management
        // Clients Management
        Route::group(['middleware' => ['role:client']], function () {
           Route::group(['namespace' => 'Client'], function () {
               Route::get('client', [ClientController::class, 'index'])->name('client.index');
          });
       });

}); // End of auth.php routes
```

And related to request i have added

`app/Http/Requests/Backend/Auth/Client/ManageClientRequest.php`

```
public function authorize()
    {
        return $this->user()->hasRole('client');
    }
```

But i still get permission error, any ideas?

**Comment by bryanrscott** [comment]
Just a couple of questions / checks that might shed some light on
Q1) Do your users have the view-backend permission?  (as required in routes/web.php)
Q2) Do your users have the admin role?  (as required by the top middleware of auth.php)
Q3) Any reason not to put in a routes/backend/clients.php?

**Comment by asantisan** [comment]
A1) Yes.-
A2) No, don't want to. Users can create their own clients but no need to have admin roles.-
A3) Created the routes/backend/clients.php with the example of routes and it keeps saying i don't have permissions being the user with the role client on + admin backend access.-

**Comment by bryanrscott** [comment]
OK, You now have a different setup?   what is the full contents of routes/backend/clients.php

**Comment by asantisan** [comment]
```
<?php
Route::group(['middleware' => ['role:client']], function () {

    // Clients Management
    Route::group(['namespace' => 'Client'], function () {
        Route::get('client', [ClientController::class, 'index'])->name('client.index');
    
    
        Route::get('client/import', [ClientController::class, 'import'])->name('client.import');
    
        Route::get('client/create', [ClientController::class, 'create'])->name('client.create');
        Route::post('client', [ClientController::class, 'store'])->name('client.store');
    
        Route::group(['prefix' => 'client/{client}'], function () {
            Route::get('/', [ClientController::class, 'show'])->name('client.show');
            Route::get('edit', [ClientController::class, 'edit'])->name('client.edit');
        });
    
    });
    
    // Tax Management
    Route::group(['namespace' => 'Tax'], function () {
    
        Route::get('tax', [TaxController::class, 'index'])->name('tax.index');
        Route::get('tax/export', [TaxController::class, 'import'])->name('tax.export');
        Route::get('tax/import', [TaxController::class, 'import'])->name('tax.import');
    });

});
```

**Comment by bryanrscott** [comment]
OK so your error could be anywhere in a number of places.   A couple of things to try
a) can an admin access the page (just to make sure working)?
b) use debugbar and see if all the gates are passing.
c) get a simple view html page working first.

**Comment by asantisan** [comment]
**a)** Page is working correctly but only admin can access.-
**b)** I tried to create new routes in the web.php router into the admin and i don't have permissions but now i get a 403 - This action is unauthorized.-
This is what i have:
```
<?php

use App\Http\Controllers\LanguageController;
use App\Http\Controllers\Backend\Client\ClientController;
use App\Http\Controllers\Backend\Tax\TaxController;
/*
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', [LanguageController::class, 'swap']);

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    include_route_files(__DIR__.'/frontend/');
});

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {

    Route::group(['namespace' => 'Client'], function () {
        Route::get('client', [ClientController::class, 'index'])->name('client.index');


        Route::get('client/import', [ClientController::class, 'import'])->name('client.import');

        Route::get('client/create', [ClientController::class, 'create'])->name('client.create');
        Route::post('client', [ClientController::class, 'store'])->name('client.store');

        Route::group(['prefix' => 'client/{client}'], function () {
            Route::get('/', [ClientController::class, 'show'])->name('client.show');
            Route::get('edit', [ClientController::class, 'edit'])->name('client.edit');
        });

    });

    Route::group(['namespace' => 'Tax'], function () {

        Route::get('tax', [TaxController::class, 'index'])->name('tax.index');
        Route::get('tax/export', [TaxController::class, 'import'])->name('tax.export');
        Route::get('tax/import', [TaxController::class, 'import'])->name('tax.import');
        Route::post('tax/store', [TaxController::class, 'store'])->name('tax.store');
    });

    include_route_files(__DIR__.'/backend/');
});
```
Notice that i change controllers path out of `Auth` folder.

**c)** I'm also getting a 403 - This action is unauthorized, i'm getting crazy here! thanks in advance.-

Extra info:

*Admin has Administrator, Clients, Taxes roles with view backend permission*
*User has Clients, Taxes roles with view backend permission*

This are the repositories/models/requests used
`app/Repositories/Backend/Auth/ClientRepository.php`
`app/Models/Auth/Client.php`
`app/Http/Requests/Backend/Auth/Client/ManageClientRequest.php`

**Comment by bryanrscott** [comment]
Don't have a solution, but maybe the problem could be made simpler, by breaking up.
In the route group admin can you add a test route, that pretty much has no dependancies.
Route::get('test', function () { . return 'Hello World'; });
and see if your user can access /admin/test

**Comment by bryanrscott** [comment]
To get a basic working example align the lines you have asked for I had to do this.  Hope this helps you out.

1) Add and entry in the model_has_permissions table
2) ./artisan permission:cache-reset
3) Modify routes/web.php adding one line (inside the route group admin line)
`    Route::get('test','TestController@index');`
4) Create a controller app/Http/Controllers/Backend/TestController.php
```
<?php
namespace App\Http\Controllers\Backend;
use Illuminate\Http\Request;
class TestController {
    public function index(Request $request) {
        return 'TEST';
    }
}
```

**Comment by asantisan** [comment]
Solved this, thanks for the help and this great boilerplate!
