### ISSUE TITLE
Does it use CDNs? Can they be easily replaced with local files? [Question]

### ISSUE THREAD

**Issue by warmwhisky** [rappasoft/laravel-boilerplate#1294]
I want to develop for an internal network app that has no internet. So CDNs can be a problem for me.

Are you using any CDNs atall?

**Comment by coderkoala** [comment]
None. It's all using webpack, look it up, you should be able to find everything you need in it.

I discourage using CDNs, a better approach always is to use npm, save the library, then import, then mix into your projects, so you can always minimize GET requests on your app.

Using webpack also means you're free to update it, and you should only have issues once every few months, resolving a few merge conflicts.

Feel free to check this out: https://laravel.com/docs/6.x/mix
