### ISSUE TITLE
CSS bug on user management page

### ISSUE THREAD

**Issue by mwkcoding** [rappasoft/laravel-boilerplate#1298]
Version 6.0.1

There's a bug on the user management page. The actions dropdown on users is hidden behind a weird overflow on the `.table-responsive` element. This is causing the delete action to not be visible. I've found a fix for it that solves the reason for the `overflow-x: auto` property AND the dropdown being inaccessible, that I will push to a PR in a few minutes. Just gotta test it a little more.

Screenshot of the bug happening:
![screenshot of bug](https://user-images.githubusercontent.com/16936030/69460155-b5c1d280-0d73-11ea-8f93-231e03a05d1b.png)

**Comment by rappasoft** [comment]
Fixed
