### ISSUE TITLE
Route [frontend.auth.customer.confirm] not defined.

### ISSUE THREAD

**Issue by faisalmalik932** [rappasoft/laravel-boilerplate#1300]
i replaced the frontend controller with the Customer controller but not able to register the customer please help me

![Capture](https://user-images.githubusercontent.com/42990977/69851893-ae993980-1237-11ea-89ba-fbc6f4897f32.PNG)
![Capture1](https://user-images.githubusercontent.com/42990977/69852191-80682980-1238-11ea-9b09-d70ff639384b.PNG)

![Capture2](https://user-images.githubusercontent.com/42990977/69852212-9249cc80-1238-11ea-81b5-9da5f6bdd3b2.PNG)

**Comment by bryanrscott** [comment]
Have you registered the route in the routes file, for example in /routes/frontend/auth.php
