### ISSUE TITLE
Laravel-Boilerplate fressh install - Everything works except User Registration 

### ISSUE THREAD

**Issue by noorcs** [rappasoft/laravel-boilerplate#1303]
I installed laravel-boilerplate. Everything is working fine, I can login as admin, create users, create roles. All is fine. Except when I logout and go to the Registration page, fill the form. When submitting the form, the following error is displayed:
`Connection could not be established with host localhost [No connection could be made because the target machine actively refused it. #10061]`
I checked my .env file. My DB settings and credentials are set properly because everything else is working.
![Screenshot (405)](https://user-images.githubusercontent.com/12681020/71642272-897e6780-2cca-11ea-9990-4a2c9058e8b6.png)
![Screenshot (406)](https://user-images.githubusercontent.com/12681020/71642274-8a16fe00-2cca-11ea-8a81-d140d2e98ff7.png)

**Comment by rappasoft** [comment]
A swift transport error has to do with you mail credentials, it is probably trying to send the registration email but can't connect to whatever mail service.
