### ISSUE TITLE
Fresh Install - phpunit - 3 Warnings about using Continue statement - Deprecated warning for each() function - not sure

### ISSUE THREAD

**Issue by noorcs** [rappasoft/laravel-boilerplate#1305]
Today I installed laravel-boilerplate again fresh.
Everything fine. Came to phpunit step and here is the result of the command:

    $ phpunit
    PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\xampp\php\pear\PHPUnit\TextUI\Command.php on line 277

    Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\xampp\php\pear\PHPUnit\TextUI\Command.php on line 277
    PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\xampp\php\pear\PHPUnit\TextUI\Command.php on line 285

    Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\xampp\php\pear\PHPUnit\TextUI\Command.php on line 285
    PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in C:\xampp\php\pear\PHPUnit\Util\Getopt.php on line 80

    Deprecated: The each() function is deprecated. This message will be suppressed on further calls in C:\xampp\php\pear\PHPUnit\Util\Getopt.php on line 80
    PHPUnit 3.7.21 by Sebastian Bergmann.

    Could not use "Codedungeon\PHPUnitPrettyResultPrinter\Printer" as printer. 

I am not much familiar with phpunit.
I don't if besides the above warnings other tests have passed or not? or is phpunit working fine int this fresh installation or not?

![Screenshot (415)](https://user-images.githubusercontent.com/12681020/71727544-6aafda80-2e5c-11ea-8b1d-425e5a643698.png)

**Comment by poseso** [comment]
Update your phpunit it seems you are using an old one

**Comment by noorcs** [comment]
OK got it. Thanks.

**Comment by vivek-23** [comment]
_For  "continue" targeting switch is equivalent to "break"._ I just changed `continue;` to `continue 2;` and it works fine now without warnings.
