### ISSUE TITLE
using permissions and roles

### ISSUE THREAD

**Issue by abdosaeedelhassan** [rappasoft/laravel-boilerplate#1312]
is there explain that how using the permissions and roles?

i have create model Posts and all their dependencies and i gives user permission , view backend, 
show Posts, edit Posts, delete Posts.
view backend work correctly so the users can access backend, but on sidebar one i clicked in Posts
i received that, the user does not has access permission

thank you

**Comment by bryanrscott** [comment]
You need to use a seeder to create permissions and roles.   You also can use a seeder to assign permissions to roles.

**Comment by abdosaeedelhassan** [comment]
Hi, thank you for reply,
i did this before, and i grant user how has the new role (view backend)
permission, the user can access the backend but can not open any ui inside
and received that the user has no access permissions, if i need to
resolve this is it by write something inside the constructor of the
controller for the same model i need to access or by create new middleware
with routes of ui and and the role inside it.

thank you
