### ISSUE TITLE
logviewer error

### ISSUE THREAD

**Issue by rabol** [rappasoft/laravel-boilerplate#1313]
# What version?
git clone 

After first login, go to the log and view:

join(): Passing glue string after array is deprecated. Swap the parameters (View: /home/vagrant/code/laravel-boilerplate/resources/views/vendor/log-viewer/bootstrap-4/show.blade.php)

**Comment by kindmedia** [comment]
in resources/views/vendor/log-viewer/bootstrap-4/show.blade.php

to find:

`@unless(empty(log_styler()->toHighlight()))`
`            $('.stack-content').each(function() {`
`                var $this = $(this);`
`                var html = $this.html().trim()`
`                    .replace(/({!! join(log_styler()->toHighlight(), '|') !!})/gm, '<strong>$1</strong>');`
`                $this.html(html);`
`            });`
`            @endunless`

replace with:

`@unless(empty(log_styler()->toHighlight()))`
`                @php`
`                    $htmlHighlight = version_compare(PHP_VERSION, '7.4.0') >= 0`
`                        ? join('|', log_styler()->toHighlight())`
`                        : join(log_styler()->toHighlight(), '|');`
`                @endphp`
`                $('.stack-content').each(function() {`
`                    var $this = $(this);`
`                    var html = $this.html().trim()`
`                        .replace(/({!! $htmlHighlight !!})/gm, '<strong>$1</strong>');`
 `               @endunless`
`                $this.html(html);`
`            });`

see also here: 
https://github.com/ARCANEDEV/LogViewer/commit/bf69f9408ecd16bb27b409eb89aec242704dce37#diff-0384f61dbe7aa49af08b5a0650719375

Greetings Tom

**Comment by aplanting** [comment]
All you have to do is to swap the implode/join, that worked for me. 
from
`.replace(/({!! join(log_styler()->toHighlight(), '|') !!})/gm, '<strong>$1</strong>');`
to
`.replace(/({!! join('|', log_styler()->toHighlight()) !!})/gm, '<strong>$1</strong>');`

**Comment by rappasoft** [comment]
Fixed
