### ISSUE TITLE
Upgrading to CoreUI Pro

### ISSUE THREAD

**Issue by InternetMedicineMan** [rappasoft/laravel-boilerplate#1319]
I'm trying to update to CoreUI Pro. It doesn't quite make sense to me. There are multiple directories but nothing seems to match the layout of the coreui directory in Boilerplate, not even close really. I'm not even sure which directory to work from there is a admin-template directory, admin-template-ajax directory, then an admin-template-starter, and admin-template-ajax-starter.

I thought the starter directories might be the ones to start with to plug into the system but there are no JS files for any of the addons in that starter paths, but the other paths are pretty bloated with additional template files.

Can anyone provide some information on upgrading? The CoreUI documentation doesn't really cover this kind of thing at all. I'd even be willing to pay someone for some consultation/documentation in this matter if you have some time for it. I'd be mostly interested not in someone doing the work but some understanding on how to do it. The file structure and which files need to be uploaded and then the process just isn't quite gelling for me.

**Comment by bryanrscott** [comment]
CoreUI is a listed dependancy in package.json.   I presume you would need to change this.
Then in resources/sass/backend/app.scss the import is listed for webpack which might need updating

**Comment by InternetMedicineMan** [comment]
Well that's what's strange is in previous posts they just said to add the Pro stuff in and rebuild. So it's like you need to leave the dependency and you are adding another layer of the pro stuff but I don't see where or how.

I could add to the resources/sass/backend/app.scss for the updated scss files, but then that would only put the scss files in play, none of the required JS files. The structure is just confusing. It seems like the "starter" themes from CoreUI don't have JS either but the template that isn't marked starter does have them along with a whole bunch of .html example files.

**Comment by bryanrscott** [comment]
I forgot to mention the js is included in resources/js/backend/app.js

**Comment by InternetMedicineMan** [comment]
So far Ive gotten this far

run
`npm i @coreui/coreui-pro`

Then in the file resources/sass/backend/app.scss replace coreui with coreui-pro
Then in the file resources/sass/backend/app.scss replace coreui with coreui-pro
Finally in packages.json change the coreui include to coreui-pro

`npm run dev`

And that was supposed to do it based on some help I got online, however this destroys the admin. Everything is a mess. It's like it's replaced but nothing is loading properly. the buttons are working but the overall layout is a mess.

I realized I never once added my "license key" that I got after buying CoreUI Pro. Maybe it's not loading? I don't know, definitely strange.

**Comment by InternetMedicineMan** [comment]
Actually when I was looking through the files I noticed that with that command by default the version loaded was CoreUI 3.0. And since this was built with CoreUI 2.1.x I assumed that might cause issues and it does. Once I started over and built it with 2.1.x everything seems to be working. So here are the updated steps:

1. Install CoreUI Pro 2.1.x with the command: `npm i @coreui/coreui-pro@^2.1.16`
2. Open file resources/sass/backend/app.scss and on line 7 change "coreui" to "coreui-pro"
3. Open file resources/js/backend/app.js and change  "coreui" to "coreui-pro"
4. Finally in packages.json change the "coreui" include to "coreui-pro" (line 18)
5. Build the site with `npm run dev` or related command for your set up

That got it to work for me so far. After rebuild my admin is intact, but I'm trying to figure out if that loads all the add-ons and features automatically or how I would add each one. This is for an internal project so if it loads everything I'm fine with it.

Still never loaded my license key anywhere, not sure what that is for.

**Comment by InternetMedicineMan** [comment]
So I find that add ons are definitely not included. However they can be added to the CoreUI package.json file and then run npm install and they will be downloaded and installed. They still aren't loaded however. 

I think that they have to be loaded in the resources/js/backend/after.js file but not exactly sure how yet. Still investigating. 

I guess this is less of an issue and more of a discovery and running stream of how to upgrade to CoreUI-Pro, however I've seen this come up as a request a few times in the Issues, so I hope this helps others.

**Comment by InternetMedicineMan** [comment]
Okay so I investigated installing one add on for the CoreUI Pro pack. Just focusing on jquery.maskedinput and I still can't get it to work.

1. I went to the package.json file for coreui-pro and added `"jquery.maskedinput": "^1.4.1",` under dependencies.
2. then I ran `npm install`
3. I went to resources/js/backend/after.js and added `import 'jquery.maskedinput';`
4. then ran `npm run dev`

Now I can actually open public/js/backend.js and I see that jquery.maskedinput is there and being called through the webpack it looks like but it still doesn't actually load. I try accessing the functions and they aren't available.

So it appears that this isn't even loading, and even if it was loading I'm not sure this is the best way since I don't necessarily need these to load on every page. I'm at a loss.

**Comment by bryanrscott** [comment]
OK, I can't help with the specifics of coreui pro.   but to add a library which you can optionally load a on a page, one option might be to

1) add the dependancy to the project's package.json
"jquery.maskedinput": "^1.4.1",
2) run "npm install"
3) identify the required files in the package
4) in /webpack.mix.js edit to add something like
mix.copy('node_modules/bootstrap-star-rating/js/star-rating.min.js', 'public/js')
    .copy('node_modules/bootstrap-star-rating/css/star-rating.min.css', 'public/css');
5) run "npm run dev"
6) on a page requiring the library
@push('after-styles')
    {{ style('css/star-rating.min.css') }}
@endpush
@push('after-scripts')
    {{ script("js/star-rating.min.js") }}
@endpush

**Comment by InternetMedicineMan** [comment]
Nice thanks @bryanrscott 

I was working my own work around by just creating a symbolic link manually from /public/js/modules/jquery.maskedinput.js to the original /node-modules/jquery.maskedinput/src/jquery.maskedinput.js

Which essentially does the same thing. However I have a feeling your way is more proper to actually create the file and recreated if it updates instead of just a symbolic link. I assume that if something updated and it wasn't available that a error might result, however with my method I would have just had a dead symbolic link and it would have been much harder to resolve the problem.

Thanks for the help and tips. This gets me working for now.
