### ISSUE TITLE
No login possible: Field 'id' doesn't have a default value 

### ISSUE THREAD

**Issue by rmunozramirez** [rappasoft/laravel-boilerplate#1321]
- I just deployed an application.
- As usual in that process I made a ```composer update```
- When I'm trying to login I get following error message:
```
SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value 
(SQL: insert into `ledgers`

(`user_id`, `user_type`, `context`, `event`, `recordable_id`, `recordable_type`, `properties`, `modified`, `extra`, `url`, `ip_address`, `user_agent`, `created_at`, `updated_at`, `pivot`, `signature`) 

values

(1, App\Models\Auth\User, 4, updated, 1, App\Models\Auth\User, and so on...
```
The form is sending an "id" =4 and an "user_id" = 4 but the QUERY 
```(SQL: insert into `ledgers` (`user_id`, `user_type`,...```
 does not have an 'id' column.

# What version?
Laravel boilerplate Version 6.03
Laravel 6.3.0

**Comment by rappasoft** [comment]
Hmm I have those versions and I can't recreate the issue.

**Comment by Skintillion** [comment]
What makes you think it's related to this repo?
