### ISSUE TITLE
The mobile navigation burger button is not working with newer versions of jquery >=v3.5.0. I had to downgrade to jQuery JavaScript Library v3.4.1 

### ISSUE THREAD

**Issue by powerthx** [rappasoft/laravel-boilerplate#1335]
If you have the same problem just downgrade the composer.json, delete the node_module folder and rerun npm.

**Comment by rappasoft** [comment]
I think using jquery 3.4.1 for now is the answer. I'll try to find a solution soon.

**Comment by poseso** [comment]
jQuery 3.5.1 fixed the problem also BS4.5

**Comment by rappasoft** [comment]
Ok cool thanks @poseso
