### ISSUE TITLE
Any plans to upgrade the laravel version to latest 7.6.1

### ISSUE THREAD

**Issue by robinflyhigh** [rappasoft/laravel-boilerplate#1336]

**Comment by rappasoft** [comment]
It has been in the works for months now. It's a ground up from scratch, the pandemic is slowing it down big time though.

**Comment by DmACKGL** [comment]
Any repository to try to help?

**Comment by abdosaeedelhassan** [comment]
Hi, thank you for your boilerplate, is there any update coming?, there are long time from last one.

**Comment by rappasoft** [comment]
Still in active development, it is a from scratch rebuild and I haven't had much time. You can see on this branch: https://github.com/rappasoft/laravel-boilerplate/tree/7.0
