### ISSUE TITLE
Menu link active not working

### ISSUE THREAD

**Issue by eskiesirius** [rappasoft/laravel-boilerplate#1341]
I checked the demo page so when you click the user management then create or edit or show the data, the sidebar menu of user management isn't active.

**Comment by eskiesirius** [comment]
It is ok now.. I just change the..

```active_class(Route::is('admin/auth*')```
to
```request()->is('admin/auth*') ? 'open' : ''```

**Comment by rappasoft** [comment]
Thanks i'll fix
