### ISSUE TITLE
InfyOmLabs/laravel-generator for laravel-boilerplate ?

### ISSUE THREAD

**Issue by kiang** [rappasoft/laravel-boilerplate#1342]
Thanks for the great job.

I've tried to use laravel-boilerplate in a new project. Just wonder if there's anyone trying to modify templates in InfyOmLabs/laravel-generator to fit the needs of laravel-boilerplate?

I'm trying to do so and it's always great to stand on the shoulder of giants. ;)

**Comment by victoriusnet** [comment]
Do you have any update on this?

**Comment by rappasoft** [comment]
I have no idea what this is.

**Comment by kiang** [comment]
Just committed the working draft. It will take some time to clean the code.
https://github.com/kiang/laravel-generator/tree/6.0

**Comment by victoriusnet** [comment]
Nice work. Is there an easy way to implement it to 7.0 later?

**Comment by kiang** [comment]
I'll wait for version 7.0 of laravel-boilerplate to be released. I just made it working based on my needs. It's not that hard to apply the changes in new version.

**Comment by victoriusnet** [comment]
@kiang 7.0 is out, are you planning to integrate it?

Thanks!
