### ISSUE TITLE
Package davejamesmiller/laravel-breadcrumbs is abandoned

### ISSUE THREAD

**Issue by robinflyhigh** [rappasoft/laravel-boilerplate#1343]
See https://github.com/davejamesmiller/laravel-breadcrumbs

**Comment by CasperBE** [comment]
https://github.com/tabuna/breadcrumbs seems a good replacement. Works almost the same and adds support for defining breadcrumbs directly in the route files

**Comment by CasperBE** [comment]
I've replaced the breadcrumbs package with `tabuna/breadcrumbs` successfully in my project based on Laravel Boilerplate

I was starting to make a PR for this but `tabuna/breadcrumbs` requires Laravel 7.

Maybe https://github.com/dwightwatson/breadcrumbs could also be a replacement (only until version 1.0.5; starting 1.1.0 Laravel 7 is also a requirement). It seems it could work as an inline replacement, though there are fewer config options, but I haven't tested this.

**Comment by rappasoft** [comment]
So i'm not going to replace on this version, but I just did on the 7.0 branch you can copy over if you wanted. It's not that much. https://github.com/rappasoft/laravel-boilerplate/commit/3e3b343fdfc134efd56a3e58f25de065d8fd9bd9
