### ISSUE TITLE
Unable to deploy to Heroku

### ISSUE THREAD

**Issue by HElwy** [rappasoft/laravel-boilerplate#1345]
Been unable to push my starter project (using boilerplate as base) to Heroku, getting the following error

```
remote:        Package manifest generated successfully.
remote:        > @php artisan ide-helper:generate
remote:        
remote:                                                                        
remote:          There are no commands defined in the "ide-helper" namespace.  
remote:                                                                        
remote:        
remote:        Script @php artisan ide-helper:generate handling the post-autoload-dump event returned with error code 1
remote:  !     WARNING: A post-autoload-dump script terminated with an error
remote: 
remote:  !     ERROR: Dependency installation failed!
```

I attempted adding the ide-helper to require also not only require-dev as that is what seems to have been the problem with several users with similar issue, but nothing changed.

**Comment by rappasoft** [comment]
It's a dev dependency, either install them or remove the calls to ide-helper from the composer scripts.

**Comment by HElwy** [comment]
It seems I missed it is mentioned in the scripts of composer.json, thank you, closing now
