### ISSUE TITLE
When repo will be upgraded to the latest version of laravel?

### ISSUE THREAD

**Issue by azeemgujjar** [rappasoft/laravel-boilerplate#1355]
When repo will be upgraded to the latest version of laravel?

**Comment by bryanrscott** [comment]
There is a 7.0 branch of the repo, that you can preview now.   I guess rappasoft will make the main when he thinks the branch is release ready.  But you can checkout now and preview.  
   
Laravel shift will update your existing app quite nicely for $15 fee.

**Comment by azeemgujjar** [comment]
ok great, I actually pull your repository but your architecture is extremely complex for no reason. things which can be handle in few files are breakdown small pieces, it's hard to integrate new modules with this architecture.
I spend several hours just to integrate a new simple CRUD module by following your pattern and it sucks..

**Comment by rappasoft** [comment]
It's structured for a larger application to scale. Use whatever project is easiest for you.

**Comment by victoriusnet** [comment]
@rappasoft Any update? What is the status of branch 7? Can it be used for production or you are planning breaking changes? Thanks!

**Comment by rappasoft** [comment]
I've been putting close to 40 hours a week into it. It was much more of a massive undertaking than I thought it would be. I would not use it for production as there are no tests.
