### ISSUE TITLE
How to created ajax route without breadcrumbs

### ISSUE THREAD

**Issue by azeemgujjar** [rappasoft/laravel-boilerplate#1360]
How to created ajax route without breadcrumbs?
Without adding route to breadcrumbs file; `Route [fetch_users] not defined`. 
link is not working how to handle this?

**Comment by rappasoft** [comment]
You do not need to add breadcrumbs for ajax routes as it is. Look like your route isn't defined.

**Comment by azeemgujjar** [comment]
Well without adding Route in breadcrumbs file no routes are working, 
can you show me any example? how to create ajax request route and in which file?
