### ISSUE TITLE
7.0

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-boilerplate#1370]
So 7.0 is definitely far along now. It's still not at the point of release by any means.

This was a ground up rebuild, like seriously `laravel new boilerplate`.

I have been working on it almost 40 hours a week in my spare time since March. I've had so many setbacks and so many do overs, but I think I finally got the majority of the functionality down that I wanted. I did not TDD this project because I didn't know what I wanted to do, so there are currently no tests, but there will be.

The single biggest items left are:

- [x] Tests
- [x] Localization - I switched from localization keys to json. I.e. __('This is the english version'), so all of the current language files are obsolete, and honestly the majority of them probably don't even apply anymore. So i'm trying to figure out what to do with those.
- [ ] I created a [Livewire tables](https://github.com/rappasoft/laravel-livewire-tables) package specifically for this boilerplate (jquery datatables replacement), which still isn't at 1.0 because I haven't had time to write the tests, so I want to get that done and to 1.0 to use in this project before release - help needed here. Otherwise works well, some small tweaks on my list.
- [x] Clean up all assets/js/sass, webpack/package files.
- [x] Fix current boilerplate issues/PR's
- [ ] Documentation Overhaul

Those are my big ticket items right now. Could you use this potentially for a new project, yeah. Would I recommend it? Not yet.

I'm calling on all tens of thousands of you who use this project as a daily driver to install 7.0 and beat the shit out of it for me. You can make PR's to that branch if you want, or if its small just drop it in here and i'll take care of it.

Keep in mind i'm constantly working on it so stuff will change as your testing.

Hope this is a welcomed update as i've been busting my ass on this for many months.

I did remove a lot of stuff from the current boilerplate for this version that I didn't see necessary anymore.

Cheers,

Anthony

P.S., these are some roadmap items:

- [ ] Authorized Devices
- [x] 2FA
- [ ] Delete account from frontend
- [ ] Admin to force password change on next login for user
- [ ] User notifications section

Just to name a few.

**Comment by bentran** [comment]
Just wanted to say keep up the good work. I'm waiting for it to start a project.

**Comment by PunchRockgroin** [comment]
I'm curious about the idea of "App\Domains"... it looks like you are following the concepts here: https://stitcher.io/blog/laravel-beyond-crud-01-domain-oriented-laravel

Can you give a very brief overview of why you chose this vs putting Models/Controllers/etc in the usual locations? I'm sure this will help others who checkout the branch and see things elsewhere in the directory tree.

**Comment by rappasoft** [comment]
I definitely think it's a worthwhile approach for large applications. You'll know exactly where all the code is for each idea and it's organized. Plus it's easy to put back to the native Laravel way with the refactor tools that PHPStorm has.

**Comment by Deceipt** [comment]
I think it’s worth moving away from the crippling forms and making a component that implements this and can simply be specified with specific ones. Or use this package
https://github.com/kdion4891/laravel-livewire-forms

**Comment by rappasoft** [comment]
What do you mean? I already have form helper components in the components/forms directory.

**Comment by rappasoft** [comment]
Decided to throw this one in: https://github.com/rappasoft/laravel-boilerplate/commit/d54e3933fda007de294be91d4b9b65a00f30dd2a

**Comment by Deceipt** [comment]
Yes it is, but the bottom line is why so many heaps of code? And reps? When you can simply implement 1 component and specify all these elements inside it. As you have now implemented work with tables, so do the forms. Just by writing 1 class and calling it, instead of sitting and writing a bunch of times the same tags and the same content

**Comment by rappasoft** [comment]
It would have been a good idea from the start, but i've been working on this for 6 months and there's no way i'm going to be redoing that much of it right now. Maybe the next version.

**Comment by victoriusnet** [comment]
@rappasoft I'm just wondering if a new main version of Laravel releasing, does it mean this boilerplate won't be easy to update? Just like now from 6 to 7 ?

**Comment by rappasoft** [comment]
Because the boilerplate is a project and not a package, there's no real upgrade guide. But definitely for the new version, it's a ground up rebuild. It will be for new projects.

**Comment by PunchRockgroin** [comment]
Any plans on a Log viewer, like before with https://github.com/ARCANEDEV/LogViewer?

**Comment by rappasoft** [comment]
There are many good log viewing plugins now, I'm leaving it up to the developer to choose their preference.

**Comment by rappasoft** [comment]
Tests are done, i'd consider it 99% if you're willing to keep the beta version of the livewire tables plugin.
