### ISSUE TITLE
7.0 Branch : Small Change Request DB Config

### ISSUE THREAD

**Issue by bryanrscott** [rappasoft/laravel-boilerplate#1379]
# Be explicit
change line 77 in config/database.php to be
'schema' => [env('DB_SCHEMA', 'public'), 'public'],

# What version?
7.0

# Example usage in .env
DB_SCHEMA=app

# Discussion
This allows a default schema for tables to be specified in the .env file. 
The array syntax in postgresql sets the search path for schema's. 
If not specified result is the same as it is now: public schema is searched / used as before.
If specified as in example the app schema will be used first before public.   (ie tables without schema references will be created in the app schema)

**Comment by rappasoft** [comment]
What's the array syntax do?

**Comment by bryanrscott** [comment]
updated request.

**Comment by rappasoft** [comment]
Sure: https://github.com/rappasoft/laravel-boilerplate/commit/d6a95ba7616d14f647ded3ed6346d886928c69d7
