### ISSUE TITLE
7.0 Problem seeding roles / permissions

### ISSUE THREAD

**Issue by bryanrscott** [rappasoft/laravel-boilerplate#1380]
# What version?
7.0

# Be explicit
The roles table has serial id, but during the seeding process specific id values are used when inserting data.  For example in the database\seeds\Auth\PermissionRoleTableSeeder
        // Create Roles
        Role::create([
            'id' => 1,
            'name' => 'Administrator',
        ]);

        Role::create([
            'id' => config('boilerplate.access.role.default'),
            'name' => 'Member',
        ]);

This throws the sequence out of whack, and when you try and create a role without specifying the id you get a "duplicate key value violates unique constraint "roles_pkey"" error.  

# Discussion
There are two ways around this.  a) always set id for the role when creating.  b) reset the value of the sequence appropriately.

Some code that might support b)
database\seeds\Auth\PermissionRoleTableSeeder.php (inserted around line 77)
`      
        // Ensure sequences are ready.....
        $max = Role::query()->max('id') + 1;
        $this->setSequenceValue(with(new Role())->getTable(), 'id', $max);
        $max = Permission::query()->max('id') + 1;
        $this->setSequenceValue(with(new Permission())->getTable(), 'id', $max);
`

database\seeds\Traits\SetSequenceValue.php
`
use Illuminate\Support\Facades\DB;

/**
 * Class SetSequenceValue.
 */
trait SetSequenceValue
{
    /**
     * @param $table
     * @param $column
     * @param int $value
     * @return bool
     */
    protected function setSequenceValue($table, $column, int $value)
    {
        switch (DB::getDriverName()) {
            case 'mysql':
                return  DB::statement('ALTER TABLE '.$table.' AUTO_INCREMENT='.$value);

            case 'sqlsrv':
            case 'pgsql':
                $sequence = $table.'_'.$column.'_seq';

                return  DB::statement('ALTER SEQUENCE '.$sequence.' RESTART WITH '.$value);

            case 'sqlite':
                $sequence = $table.'_'.$column.'_seq';

                return DB::statement('sqlite_sequence SET '.$sequence.' = '.$value);
        }

        return false;
    }
}`

**Comment by rappasoft** [comment]
Why would you let the user set the primary key?

**Comment by bryanrscott** [comment]
updated comment to include existing code causing issue in database\seeds\Auth\PermissionRoleTableSeeder

**Comment by rappasoft** [comment]
A fresh database should have no problem seeding ID 1 for the admin role and ID 1 for the admin user.

**Comment by bryanrscott** [comment]
Agree, but substantially when I go to seed my own roles the issue arises

**Comment by rappasoft** [comment]
Can not replicate:

Added to the seeder:

`Role::create(['name' => 'Three']);
        Role::create(['name' => 'Four']);
        Role::create(['name' => 'Five']);
        Role::create(['name' => 'Six']);
        Role::create(['name' => 'Seven']);`

Seeds fine:

<img width="561" alt="Screen Shot 2020-06-16 at 09 12 22" src="https://user-images.githubusercontent.com/6026504/84778852-914c7280-afb1-11ea-92b5-edaaf32edc58.png">

**Comment by bryanrscott** [comment]
It might be a postgresql specific.

**Comment by hariadi** [comment]
If you have database master-master replication with custom configuration for example `mysql`:
```
auto_increment_increment=2
auto_increment_offset=1
```

The ID need to take dynamically.
