### ISSUE TITLE
Error in migrating

### ISSUE THREAD

**Issue by Neelam3dot14** [rappasoft/laravel-boilerplate#1394]
Not able to found 
2020_04_02_000000_create_two_factor_authentications_table.php file in migration 
showing error in migration please resolve  ASAP 
![image](https://user-images.githubusercontent.com/65005545/86224872-0f5e6b00-bba7-11ea-845e-60539cb9cc52.png)

**Comment by bryanrscott** [comment]
Can you check your mariadb version?  from https://mariadb.com/kb/en/json-data-type/ you need version 10.2.7 or greater?
alternatively you could edit the migration and change the type from json to text?

**Comment by bryanrscott** [comment]
the migration is in vendor/darkghosthunter/laraguard/database/migrations.
 https://github.com/DarkGhostHunter/Laraguard

**Comment by rappasoft** [comment]
There is nothing wrong with the migration or boilerplate: https://mariadb.com/kb/en/json-data-type/
