### ISSUE TITLE
Mix...

### ISSUE THREAD

**Issue by themcgarvie** [rappasoft/laravel-boilerplate#1395]
No matter what solutions I try, I can not get 'npm run dev' to work.

This is a fresh download of boilerplate.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-03T08_02_27_075Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-03T08_02_27_215Z-debug.log

**Comment by bryanrscott** [comment]
does "npm install" complete successfully for you?

**Comment by rappasoft** [comment]
Just downloaded a new project and worked fine in Valet:

`
> @ dev /Users/Rappa/Documents/Programming/Local/GitHub/Boilerplate
> npm run development


> @ development /Users/Rappa/Documents/Programming/Local/GitHub/Boilerplate
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 DONE  Compiled successfully in 19442ms8:21:43 PM

                                                                                              Asset      Size        Chunks             Chunk Names
                                                                                     /js/backend.js   832 KiB   /js/backend  [emitted]  /js/backend
                                                                                    /js/frontend.js   913 KiB  /js/frontend  [emitted]  /js/frontend
                                                                                    /js/manifest.js  14.4 KiB  /js/manifest  [emitted]  /js/manifest
                                                                                      /js/vendor.js   3.3 MiB    /js/vendor  [emitted]  /js/vendor
                                                                                    css/backend.css  1.24 MiB  /js/frontend  [emitted]  /js/frontend
                                                                                   css/frontend.css  1.89 MiB  /js/frontend  [emitted]  /js/frontend
                  fonts/vendor/@coreui/icons/CoreUI-Icons-Free.eot?564bebeb830380152ae12fe898819ae5   102 KiB                [emitted]  
                  fonts/vendor/@coreui/icons/CoreUI-Icons-Free.svg?16cabe3d0fd259e780e723f7b0bfedd1   340 KiB                [emitted]  
                  fonts/vendor/@coreui/icons/CoreUI-Icons-Free.ttf?45f25dff67e13b624e0b01c60cd71cd1   102 KiB                [emitted]  
                 fonts/vendor/@coreui/icons/CoreUI-Icons-Free.woff?653e1aa55a9603c97204f607e66a095c   102 KiB                [emitted]  
   fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.eot?4a5d4d855d11fae79cc864bdacb2f479   132 KiB                [emitted]  
   fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.svg?778b1f251bea7412048da95b87bf816f   712 KiB                [emitted]  
   fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.ttf?4c1da237bdae0773309df93b2cd48e09   131 KiB                [emitted]  
 fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.woff2?91a23e8bf2b4b84c39311cb5eb23aaa0  75.6 KiB                [emitted]  
  fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.woff?5734d789b25228cbafc64a58ae971aca  88.7 KiB                [emitted]  
  fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.eot?6b20949b3a679c30d09f64acd5d3317d  33.6 KiB                [emitted]  
  fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.svg?66578cdbb6dc01f527a53971051b3e85   141 KiB                [emitted]  
  fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.ttf?260be4f29c0b2ce47480afb23f38f237  33.3 KiB                [emitted]  
fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.woff2?5c674c9216c06ede2f618aa58ae71116  13.3 KiB                [emitted]  
 fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.woff?d44ad00c44e46fd29f6126fa7d888cde  16.4 KiB                [emitted]  
    fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.eot?9a1672a8a8d91fbf82c71f451d495253   200 KiB                [emitted]  
    fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.svg?486853107489520b3265b19b191626f8   889 KiB                [emitted]  
    fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.ttf?c65d154888aa166982dac3e72e7380ec   200 KiB                [emitted]  
  fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.woff2?412a43d6840addd683665ec12c30f810  78.4 KiB                [emitted]  
   fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.woff?f3a7d3b5880544a91e9a7e6f8f35d4d2   102 KiB                [emitted]  
`

**Comment by rappasoft** [comment]
I get your exact error if I run `npm run dev` before `npm install`

**Comment by themcgarvie** [comment]
After much faffing about, i resorted to upgrading node to 12.6.3 and works, failed to work with an earlier 12.x and a 9.x and an 8.x ... very frustrating.

**Comment by bryanrscott** [comment]
Works with the latest version of Homestead

**Comment by themcgarvie** [comment]
That's nice for people using Homestead.

> 
> 
> Works with the latest version of Homestead
