### ISSUE TITLE
V7 Routes

### ISSUE THREAD

**Issue by bryanrscott** [rappasoft/laravel-boilerplate#1399]
Just want to confirm that route:resource and route:apiResource are not able to be used at present with Controllers in the App\Domains

**Comment by rappasoft** [comment]
Why's that?

**Comment by bryanrscott** [comment]
Might be I found the correct syntax

If I try
Route::resource('signer', SignerController::class);
I get
Target class [App\Http\Controllers\Frontend\App\Domains\Tuflic\Http\Controllers\Frontend\SignerController] does not exist.

If I try
Route::resource('signer', [SignerController::class]);
I get artisan route:cache
Route cache cleared!
Array to string conversionRoutes cached successfully!

So I presume it is not right?

**Comment by rappasoft** [comment]
Did you make sure the route group you're in isn't appending a namespace as most of mine do?

The ::class syntax will just echo the full namespace, so it will get appended to where ever you're calling the route. You can try the full namespace with the trailing slash to break out of the namespace:

i.e. `Route::resource('signer', '\My\Full\Namespace\SignerClass');`

**Comment by bryanrscott** [comment]
Understand thanks

**Comment by bryanrscott** [comment]
Actually I am still having an issue.  Would you mind providing an example?
I am trying to get this working in routes/frontend/home.php

//Route::get('/', [HomeController::class, 'index'])->name('index');
Route::resource('/', HomeController::class)->only(['index']);

**Comment by bryanrscott** [comment]
At the moment rewriting all my route files, replacing the single line Route::Resource with

Route::group(['as' => 'notification.', 'prefix' => 'notification'], function () {
        Route::get('', [NotificationController::class, 'index'])->name('index');
        Route::get('create', [NotificationController::class, 'create'])->name('create');
        Route::post('', [NotificationController::class, 'store'])->name('store');
        Route::group(['prefix' => '{id}', 'where' => ['id' => '[0-9]+']], function () {
            Route::get('', [NotificationController::class, 'show'])->name('show');
            Route::get('edit', [NotificationController::class, 'edit'])->name('edit');
            Route::match(['PUT', 'PATCH'], '', [NotificationController::class, 'update'])->name('update');
            Route::delete('', [NotificationController::class, 'destroy'])->name('destroy');
        });
    });
