### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by Neelam3dot14** [rappasoft/laravel-boilerplate#1407]
The password was found in a third-party data breach, and can not be used.
This is coming for admin and for any user if I am trying to change the password . How to resolve please suggest

**Comment by rappasoft** [comment]
It's being triggered by this package: https://github.com/langleyfoxall/laravel-nist-password-rules

You can remove the package and replace it with your own password rules.

**Comment by Neelam3dot14** [comment]
Actually I need to know on which condition this message is showing so I should avoid that

**Comment by rappasoft** [comment]
The BreachedPasswords rule securely checks the password against previous 3rd party data breaches, using the [Have I Been Pwned - Pwned Passwords API](https://haveibeenpwned.com/Passwords).
