### ISSUE TITLE
Two-factor Authentication not working

### ISSUE THREAD

**Issue by azeemgujjar** [rappasoft/laravel-boilerplate#1410]
Two-factor Authentication verification not working i tried with google auth, and free otp

**Comment by SuperlativeEntity** [comment]
Worked for me

**Comment by nouart** [comment]
Two-factor Authentication verification not working  too  !!

**Comment by Hnyshri** [comment]
How to Generate a code from your 2FA app???

**Comment by Hnyshri** [comment]
Its working...

You need install the Google Authenticator and scan the ORcode then got the code...
