### ISSUE TITLE
Bootstrap not complete?

### ISSUE THREAD

**Issue by InternetMedicineMan** [rappasoft/laravel-boilerplate#1411]
I'm really enjoying Boilerplate as a framework. However I've noticed that a lot of the default things that come with Bootstrap seem to be missing? 

Collapse doesn't work
Modals don't work

Just finding several elements of bootstrap that are normally default just don't work. Is there something I'm missing? Is there some element that I need to load or add in to bring additional elements in? Any advice or pointing in the right direction would be helpful, I know this doesn't relate to boilerplate core programming but I'm hoping there is some advice here from someone as it's not apparent to me what is missing so it's hard to get assistance in the Bootstrap community.

**Comment by poseso** [comment]
which BP version?

**Comment by rappasoft** [comment]
Are you sure? I just copied and pasted the default modal out of the bootstrap docs onto the login page and it worked. Here's a video:

https://a.uguu.se/LFaxpdXGYFus_ScreenRecording2020-07-20at22.43.04.mov

**Comment by InternetMedicineMan** [comment]
Yeah I'm positive, I add the classes per the documentation and nothing happens. I did try to upgrade to CoreUI Pro could that have messed something up? The bootstrap include seems to be unchanged. But neither of these functions work at all.

**Comment by rappasoft** [comment]
Really weird, I'm using the new version on a few projects with all the bootstrap addons and I didn't have to install anything specific. Let me know if you figure anything out.
