### ISSUE TITLE
Suggestion for delete action

### ISSUE THREAD

**Issue by abdosaeedelhassan** [rappasoft/laravel-boilerplate#1414]
by taking advantage of livewire and not reload the page, may be something like next

`<button onclick="confirm('Are you sure! you want to delete this') || event.stopImmediatePropagation()"
        wire:click="destroy({{$row->id}})" class="btn btn-sm btn-danger"><i class="fas fa-trash" data-toggle="tooltip" data-placement="top" title="' . __('buttons.general.crud.delete') . '"></i></button>`

and adding destroy method inside table component, i don't know how to implemented confirm message using sweetalert2 package, i think will be better

**Comment by rappasoft** [comment]
A good suggestion i'll keep it in mind
