### ISSUE TITLE
Guide for Migrate/Upgrade

### ISSUE THREAD

**Issue by sukarno1234** [rappasoft/laravel-boilerplate#1415]
I am currently working with boilerplate 5.4 for years until now and want to upgrade. Is there a guide for upgrading it slowly?? I would appreciate any help. Thank you.

**Comment by rappasoft** [comment]
There would be no way to upgrade to the newest version from that. You would have to start with a fresh install and port your classes over. This is a template project not a plugin.

**Comment by bryanrscott** [comment]
Having done it, I have to agree with @rappasoft at some stage you will need start with a fresh install and port you classes over.   But if your not ready for that step there are a few smaller steps that you can do now on your code, that will help you.   Basically they help align your code with the new boilerplate code, which in turn makes porting to a fresh install much easier.

Possible Interim Steps
a) Update your codebase to laravel 7.  This is pretty well documented.   Or spend the $15 to get laravel shift to do for you (it is kinda worth getting it to do it even if you want to manually do each step, as it will give you a road map to achieve this).   But this is kinda a must do first step.

b) Move from Repository to Services.   Backport the BasService and use it to replace and rename all the repository classes you have.

c) Restructure your files in \app into \app\Domains (you can do this piecemeal and over time).   It means reorganising your routes, etc.   A word of caution on the resource routes as these need to be expanded, I have a open issue on.

d) Refactor out into seperate classes any customisations you have (custom user attributes etc) as much as possible.  For example.   I have an app\Domains\App\Models\Traits\AppUser that I put my custom extensions to attributes, method, relationship and scope.   Not sure about the app\Domains\App naming.

You would be much closer to port to a clean install once you have done these.   It means many of the ports will be just a copy of your files across.
Once you have done the port for features that were dropped that you use, eg the contact form,  I just backported the laravel 6 version of and put in the App domain.

**Comment by sukarno1234** [comment]
> There would be no way to upgrade to the newest version from that. You would have to start with a fresh install and port your classes over. This is a template project not a plugin.

Thank you for replying. Where can I get the Boilerplate Laravel 5.8??

**Comment by bryanrscott** [comment]
https://github.com/rappasoft/laravel-boilerplate/tags
