### ISSUE TITLE
2FA Middleware Path Check

### ISSUE THREAD

**Issue by ramesesniblick3rd** [rappasoft/laravel-boilerplate#1425]
Just a trivial issue but the TwoFactorAuthenticationStatus middleware only checks the route `$request->is('admin/*')`. So when using `example.com/admin` without any further paths it requires 2fa to be enabled regardless of the config settings.

Probably not an issue for most but it was confusing me for a while, thinking there was something wrong with the config.

**Comment by rappasoft** [comment]
Hmm shouldn't it still fail if you have the config off because it's an AND check? What would fix your issue? Making it **admin*** instead of **admin/***?

**Comment by ramesesniblick3rd** [comment]
Bare with me Im not too experienced with anything past the basics. In app/Http/Kernel.php under the admin group it has `2fa:enabled` and commented above says to edit the config instead of disabling that. So `$status === 'enabled'` would always be true.

In the middleware the path would fail, the next part checks if status is enabled (true) and redirects to create 2fa if the user hasnt set it up.

I used `($request->is('admin/*') || $request->is('admin'))` to not interfere with whatever routes might contain admin* for some reason. But you could also move the redirect route outside the admin group

**Comment by dhonxean** [comment]
Hello. I've also tried and failed to disable 2FA even though I've disabled it from boilerplate and the middleware. Could you give us a guide on how to disable / enable it properly? Love you work man. Thank you so much for it.

**Comment by ramesesniblick3rd** [comment]
> 
> 
> Hello. I've also tried and failed to disable 2FA even though I've disabled it from boilerplate and the middleware. Could you give us a guide on how to disable / enable it properly? Love you work man. Thank you so much for it.

You dont need to edit anything other than adding `ADMIN_REQUIRES_2FA=false` to your .env then `php artisan config:clear`
As mentioned in the issue, if you try use exactly `/admin` it will redirect you to create a 2fa if none was created. Otherwise everything else works fine.

**Comment by Mohalidesigns** [comment]
ADMIN_REQUIRES_2FA=false worked @ramesesniblick3rd Thanks
