### ISSUE TITLE
Incorrect CSS for RTL languages

### ISSUE THREAD

**Issue by arnonm** [rappasoft/laravel-boilerplate#1430]
With RTL languages, there are some design issues that crop up due to the Bootstrap CSS classes.
Some examples (using the register form as an example)

Header - in LTR languages it is
APP_Name                                 Language_Dropdown    Login.  Register
In RTL it should be 
Register       Login      Language_Dropdown                                    App_Name
but instead it is
                                                       Register Login Language_Dropdown App_Name

Similarly for the Card Header

Fro the Checkbox and sentance "I agree to the terms and conditions" the text is overlapping the checkbox

All of these are due to the CSS classes which user justify-left hardcoded, and not are not direction sensative
As an example:

.form-check-input {
  position: absolute;
  margin-top: 0.3rem;
  margin-left: -1.25rem;
}

**Comment by rappasoft** [comment]
I'm not a CSS RTL expert, but if you have time and want to make fixes and a PR i'll merge it.
