### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by xnekv03** [rappasoft/laravel-boilerplate#1433]
Would it be possible to add LDAP (Active Directory) authentication?
Thank you

**Comment by bryanrscott** [comment]
There a couple of laravel modules that you might be helpful (and there might be others)
https://github.com/DirectoryTree/LdapRecord-Laravel
https://github.com/jotaelesalinas/laravel-adminless-ldap-auth

**Comment by rappasoft** [comment]
Yeah this isn't something i'll add because less than 5% of people will need it, but there should be no issue using a plugin, you should have to alter anything but the auth provider.

**Comment by bryanrscott** [comment]
Agree.
