### ISSUE TITLE
What is x-utils in the blade templates?

### ISSUE THREAD

**Issue by XGhozt** [rappasoft/laravel-boilerplate#1434]
I was having trouble tracking down where these tags are processed, could you point in the right direction?
I'm curious how they get rendered.

Example:

`<x-utils.link class="card-header-action" :href="route('admin.auth.user.index')" :text="__('Back')" />`

**Comment by bryanrscott** [comment]
check resources/views/components/utils directory

**Comment by XGhozt** [comment]
Thanks @bryanrscott -- but where does it translate `<x-utils />` into that component? 
Where is the code that points `.link` to `link.blade.php`?

**Comment by XGhozt** [comment]
Oh I see this is part of Laravel 7 now, okay.

**Comment by bryanrscott** [comment]
My understanding is that it is a standard laravel feature
https://laravel.com/docs/7.x/blade#components
