### ISSUE TITLE
SQL Server Migration error

### ISSUE THREAD

**Issue by aaly00** [rappasoft/laravel-boilerplate#1436]
I am having an issue with running the migrations to SQL Server

Migrating: 2020_02_25_034148_create_permission_tables

   Illuminate\Database\QueryException

  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Introducing FOREIGN KEY constraint 'permissions_parent_id_foreign' on table 'permissions' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints. (SQL: alter table "permissions" add constraint "permissions_parent_id_foreign" foreign key ("parent_id") references "permissions" ("id") on delete cascade)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|

      +11 vendor frames
  12  database/migrations/2020_02_25_034148_create_permission_tables.php:34
      Illuminate\Support\Facades\Facade::__callStatic()

**Comment by rappasoft** [comment]
I'll be honest this isn't tested on SQLServer. If you figure out what's wrong feel free to make a PR to fix it. I don't personally use or have access to it.
