### ISSUE TITLE
User "Name" not available?

### ISSUE THREAD

**Issue by InternetMedicineMan** [rappasoft/laravel-boilerplate#1438]
I'm trying to understand how this is all set up. If I look up a user and do a dump I get all of the data in the dump like so:

![image](https://user-images.githubusercontent.com/689814/90571336-2cf78c00-e177-11ea-86fd-9e874b2249a7.png)

But what's strange is if I try to just echo the user or access any of these fields they are different and specifically the "name" and "full name" fields are NULL instead of matching what is in the database or in the dump:

![image](https://user-images.githubusercontent.com/689814/90571534-924b7d00-e177-11ea-83e5-28b281e70a55.png)

So what's going on here and why isn't the Name passed through? Is there a bug? Am I doing something wrong?

**Comment by InternetMedicineMan** [comment]
Found the problem in /app/Models/Auth/Traits/UserAttribute.php starting in line 31:

`    /**
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->last_name
            ? $this->first_name.' '.$this->last_name
            : $this->first_name;
    }

    /**
     * @return string
     */
    public function getNameAttribute()
    {
        return $this->full_name;
    }

`

Changing the section it to just:

`    /**
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->name;
    }
`

Get's it all fixed up. Naturally don't need "full name" any longer this seems to be remnants of the previous version, however if I remove full name I get other issues so it's called elsewhere and I just left it for ease.

**Comment by rappasoft** [comment]
Thanks. This is for an older version I assume, the current version does not have first and last names separate for the user. But this will help others find this issue.

**Comment by InternetMedicineMan** [comment]
This was on the latest and greatest when I posted this issue. And you are right that the version did not have first and last names separate for the user but the code was still handling it that way which was the source of the issue.
