### ISSUE TITLE
Cannot add new roles

### ISSUE THREAD

**Issue by perffy** [rappasoft/laravel-boilerplate#1441]
Hi guys,

I have searched the previous issues, but I couldn't find a solution.
My need is to add a new user type, as also a new role and specific permissions.

I have installed a new Laravel Boilerplate 7.
In App\Domains\Auth\Models\User i have added a new user type like that:
`public const TYPE_DOCTOR = 'doctor';`

than I have changed the users migration:
`$table->enum('type', [User::TYPE_ADMIN, User::TYPE_USER, User::TYPE_DOCTOR])->default(User::TYPE_USER);`

and in the PermissionRoleSeeder i am creating the new Role:
```
Role::create([
            'id' => 1,
            'type' => User::TYPE_DOCTOR,
            'name' => 'Doctor',
        ]);
```

Unfortunately, the roles table is of type  enum('admin', 'user'). But I don't know how to change that (except creating a migration with altering this table). Is there any better solution?

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-boilerplate/blob/master/database/migrations/2020_02_25_034148_create_permission_tables.php#L22

**Comment by perffy** [comment]
thank you @rappasoft i was searching for roles migration file :)

**Comment by rappasoft** [comment]
No problem!
