### ISSUE TITLE
Two-factor authentication doesn't work

### ISSUE THREAD

**Issue by panfil3** [rappasoft/laravel-boilerplate#1442]
Your authorization code was invalid. Please try again.

**Comment by dhonxean** [comment]
It worked for me. I used 2FAS Auth

**Comment by Mohalidesigns** [comment]
2fa is not working, the response i get is "Your authorization code was invalid. Please try again.""

Pls help

**Comment by suwitolt** [comment]
It work for me.
Please check your console log.
make sure there are no error about livewire

If your project not in root directory or in sub folder, you have to run this command :

**php artisan vendor:publish --force --tag=livewire:assets**

and then edit config file in **config/livewire.php**
edit '**asset_url**'. set the value to you public folder of your project.

**Comment by bryanrscott** [comment]
I note an issue on laraguard about when using postgresql backend.
https://github.com/DarkGhostHunter/Laraguard/issues/43
