### ISSUE TITLE
Can You add a laravel mix configuration for dynamic import of vuejs components,.

### ISSUE THREAD

**Issue by AbingPj** [rappasoft/laravel-boilerplate#1446]
Thanks for the great project,. 
i fount how to use it here https://laravel-news.com/using-dynamic-imports-with-laravel-mix ,.
but got error when i applied it on laravel-boilerplate project.

**Comment by rappasoft** [comment]
I think this is easily enough added to your own project. Besides, i'm not sure how long Vue is going to stay default in the BP.

**Comment by AbingPj** [comment]
> I think this is easily enough added to your own project. Besides, i'm not sure how long Vue is going to stay default in the BP.

Okay,. thanks
