### ISSUE TITLE
error phpunit TestRunner::doRun() must be of the type array, bool given

### ISSUE THREAD

**Issue by nachete1987** [rappasoft/laravel-boilerplate#1447]
on a fresh install, when I execute phpunit I obtain the error:

hostname@machine:~/webapps/hostname$ phpunit
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to PHPUnit\TextUI\TestRunner::doRun() must be of the type array, bool given, called in /usr/share/php/PHPUnit/TextUI/Command.php on line 200 and defined in /home/hostname/webapps/hostname/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:120
Stack trace:
#0 /usr/share/php/PHPUnit/TextUI/Command.php(200): PHPUnit\TextUI\TestRunner->doRun()
#1 /usr/share/php/PHPUnit/TextUI/Command.php(159): PHPUnit\TextUI\Command->run()
#2 /usr/bin/phpunit(42): PHPUnit\TextUI\Command::main()
#3 {main}
  thrown in /home/hostname/webapps/hostname/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 120

**Comment by rappasoft** [comment]
Weird but more related to your setup somehow as all the tests in the actions pass.

If you're not, and have access to a mac, you should definitely try with Valet or Homestead.

**Comment by khafidmedheb** [comment]
HI,
 I had the same error with Phpunit version > 8.
I solved it by installing (composer require) the package phpunit/phpunit version "^7" at first with composer.
Hope it helps !.

**Comment by StevenCarre** [comment]
Hi,
I got the same error exactly on Symfony. Downgrading doesn't work for me, as one downgrade leads to another and finally you end up trying to install a package that is not maintained anymore and composer can't find it. Anybody managed to solve this issue?

**Comment by najd-mrabet** [comment]
maybe you forgot to copy phpunit.xml.dist to phpunit.xml
