### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-boilerplate#1449]
Hello All,

First off there are at least 5 packages used in the BP that do not have 8.0 support yet, so I can not upgrade. I'm trying to weigh if we need these packages or if they are small enough to remove and do myself.

Regardless i'll have to wait for some, and I also want to swap Laraguard out for Fortify, which will be time consuming.

Secondly I wanted some feedback regarding Jetstream. I think it is a super powerful UI stack that will most likely take a lot of the user base from this project. Which is fine because the whole purpose of this project was a big head start, which is what Jetstream is.

So i'm trying to decide if maintaining this project is something i'm going to continue in the future or if most of you are just going to use Jetstream for your next project. Be honest, you won't hurt my feelings.

That being said, if not, the next major version of this project I would most likely go the Jetstream route and remove Bootstrap and CoreUI for a custom Tailwind template powered with Livewire.

So please give me your thoughts on the future of this project, good or bad.

Thanks

**Comment by bryanrscott** [comment]
I think this project brings a nice structure for medium to large projects on top of laravel, and if continued would continue to base off.    We use the defaults and extend for /admin and so would probably follow if you went tailwind etc in the /admin
For our user facing portions however we would maintain bootstrap.

**Comment by ramesesniblick3rd** [comment]
I briefly tried Jetstream and love that it uses Tailwind out of the box. Its simple, lightweight and very easily customizable. It feels very much like "heres all the tools now go create something beautiful!"

[Rant about bootstrap] Almost every site that uses Bootstrap looks the same, with the instantly recognizable buttons, cards and jumbatrons. The very first thing I did when using laravel-boilerplate was replace the front end with Tailwind. IMO Bootstrap is great for quickly laying something out without a need to make it different or care much about having a unique front-end. Unless you bloat it more than it already is. However I have yet to try the Bootstrap 5 alpha so that could change things. [/Rant about bootstrap]

The key thing Jetstream misses for my usage is the lack of differentiating roles/permissions with a separate back/front-end by default, which is understandable. I think laravel-boilerplate provides these missing pieces perfectly by default. Being able to go straight into your actual content without having to mash together yet another basic user/admin system is a great help and motivator.

So for me a future project of a Jetstream based laravel-boilerplate sounds very good.

**Comment by babul** [comment]
I would vote for Jetstream and Tailwind approach. I prefer Tailwind to Bootstrap for new apps going forward.

**Comment by mikimaine** [comment]
I think this project will still have a place, there are a lot of features that are still missing from Jetstream. I think it is the right time to remove core UI and have a custom theme that uses tailwind.

**Comment by dukenst2006** [comment]
This project is always valuable, i vote for it to stay alive and move to Jetstream and tailwinds CSS approach, it will be nice to offer some missing Jetstream features on the admin perspective. Thx

**Comment by xihad76** [comment]
+1 for the boilerplate based on jetstream. Jetsream is cool but still misses some starter features which this project nicely covers. I would surely like to see this project going forward and provide us the best of both worlds.

**Comment by rappasoft** [comment]
I appreciate the responses so far. My original intent was not to start with Jetstream and add on to it, but to rather mold the current boilerplate to be more like Jetstream.

However, thinking about it the former might be the way to go, i'm not sure yet. Either way it would be a massive undertaking. The current version took me 5 months and hundreds of hours. I'm finding it harder and harder to make the time to even do the updates.

I'm not sure what the Jetstream upgrade process would be like, and if I use and customize it, is it just stuck in that version? Or would I have to re-customize all the views it comes with every time I upgrade? Who knows yet.

**Comment by babul** [comment]
I just discovered this project yesterday, and look forward to spending some time with it soon. I have my own basic starter, and I use Laravel Nova for some projects. 

Might be worth letting the swirl around Jetstream, and Laravel 8 for that matter, ease after a few weeks to evaluate how best to refactor. :D Always a flurry of activity after major releases, and from Taylor's tweets, he's exploring ways to ease some customizations/integrations.

Jetstream when enabling Teams appears to have some overlaps with Spatie permissions (https://jetstream.laravel.com/1.x/features/teams.html#roles-permissions).

**Comment by SakuraCart** [comment]
@rappasoft I really appreciate all your time and what you have done for the community.

I haven't used boilerplate yet on a site but I have played with the code on and off over the years.
When Nova came out I wondered if this project would disappear. Jetstream shows up and there is talk about what to do.

I think that there is still a space for boiler plate, so, why not let the project evolve?

**Comment by rickmills** [comment]
In terms of just getting the current version compatible with Laravel 8 it's so close to being possible. Running the `composer.json` file through the [Laravel shift upgrade checker](https://laravelshift.com/can-i-upgrade-laravel) shows that we're now only waiting on [albertcht/invisible-recaptcha](https://github.com/albertcht/invisible-recaptcha). 

Theres already [a pull request](https://github.com/albertcht/invisible-recaptcha/pull/136) that works with L8 so we're just waiting on @albertcht to approve it.

As soon as that's done Boilerplate will work on Laravel 8 and Livewire 2.

**Comment by rappasoft** [comment]
I appreciate all the feedback!
