### ISSUE TITLE
Redirect loop when integrating saml 

### ISSUE THREAD

**Issue by mohanrvgit** [rappasoft/laravel-boilerplate#1451]
Hi 

I have installed the package and its working fine. But when integrating with saml, the redirect loop happens. I tried a lot to figure out the issue but no clues. Could you please help me to solve?

Thanks
Mohan RV

**Comment by farhana-lucky** [comment]
Sure

**Comment by rappasoft** [comment]
This does not seem like an issue specific to this project.
