### ISSUE TITLE
Slack channel link 

### ISSUE THREAD

**Issue by dregad** [rappasoft/laravel-boilerplate#1453]
Hello,

The link to join the Slack channel (https://laravel-boilerplate.herokuapp.com/), referenced in 
- README.md
- Website https://laravel-boilerplate.com/ 
does not seem to offer any means to get an invite.

Looking at [Git history](https://github.com/rappasoft/laravel-boilerplate/commit/314a46cfe1b4eb5b0bf705be08a3de0dec12880f#diff-0730bb7c2e8f9ea2438b52e419dd86c9L23) I found the old link https://laravel-5-boilerplate.herokuapp.com/ which does work.

Not sure whether you'd want to update the references in the above-mentioned locations, or the code hosted at https://laravel-boilerplate.herokuapp.com/, but the current situation is somewhat confusing and needs to be fixed.

Cheers
Damien

**Comment by dregad** [comment]
Related to #1408

**Comment by rappasoft** [comment]
I fixed it on the website, i'll fix the readme on the next release. The link in the github description is still right.
