### ISSUE TITLE
Improperly localized strings

### ISSUE THREAD

**Issue by dregad** [rappasoft/laravel-boilerplate#1456]
Testing the code with a French setup, I noticed that there are quite a few strings for which there is apparently no localization

![image](https://user-images.githubusercontent.com/449891/94988866-afde7580-0570-11eb-92e3-ba7feeed5315.png)
![image](https://user-images.githubusercontent.com/449891/94988903-e74d2200-0570-11eb-80a1-dc5685cf1491.png)

**Comment by dregad** [comment]
When registering a new user
![image](https://user-images.githubusercontent.com/449891/95011327-29896880-0630-11eb-9abf-84c00dbe5275.png)

When deleting a user
![image](https://user-images.githubusercontent.com/449891/95011406-c2b87f00-0630-11eb-8445-fe8d26ccd604.png)

**Comment by rappasoft** [comment]
The whole thing is localized. I only speak on language and rely on the community to make PR's to fix the rest. Feel free to fix whatever you see. As for the password rules, those come from a package and you will most likely have to publish that packages language files (if they have any).
