### ISSUE TITLE
Name column empty depending on language

### ISSUE THREAD

**Issue by dregad** [rappasoft/laravel-boilerplate#1457]
When displaying Users (/admin/auth/user route) or Roles (/admin/auth/role route), the _Name_ column does not display any data depending on the currently selected language (e.g. for French, Spanish, Italian...)

![image](https://user-images.githubusercontent.com/449891/95011533-aa952f80-0631-11eb-9fb1-469e20ea2da4.png)

In English, German (and some other languages too, did not test all), everything is OK

![image](https://user-images.githubusercontent.com/449891/95011553-d3b5c000-0631-11eb-8ef2-13bb8f96f993.png)

**Comment by dregad** [comment]
If I click on the column header, I get

Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nom' in 'order clause' (SQL: select `roles`.*, (select count(*) from `users` inner join `model_has_roles` on `users`.`id` = `model_has_roles`.`model_id` where `roles`.`id` = `model_has_roles`.`role_id` and `model_has_roles`.`model_type` = App\Domains\Auth\Models\User and `users`.`deleted_at` is null) as `users_count` from `roles` order by `nom` asc limit 25 offset 0)

**Comment by DediTaryadi** [comment]
I tried to check app/Http/Livewire/RolesTable.php

and change
```
Column::make(__('Name'))
                ->searchable()
                ->sortable(),
```

into

```
Column::make(__('Name'),'name')
                ->searchable()
                ->sortable(),
```

its working, and there is already [PR #1450](https://github.com/rappasoft/laravel-boilerplate/pull/1450) for this.

**Comment by dregad** [comment]
@kangdetar thanks for the feedback. Somehow I missed #1450, indeed the proposed fix addresses both the issue in the opening comment, and the QueryException.
