### ISSUE TITLE
Localize String Error

### ISSUE THREAD

**Issue by tuluong** [rappasoft/laravel-boilerplate#1459]
Hi There!

I've got an issue about the @lang('Roles')  , it always raise **ErrorException
Array to string conversion** wherever the 'Roles' translation rendering. Is there anybody know where to fix this?

Thanks

**Comment by bryanrscott** [comment]
I got this error in a couple of circumstances
a) when I had a translation file of the same name
b) when the translation clashed in one of the resources/lang/ files 

A quick fix till you find the issue @lang('RolesREPLACEME').  then you can come back and search and replace

**Comment by tuluong** [comment]
> I got this error in a couple of circumstances
> a) when I had a translation file of the same name
> b) when the translation clashed in one of the resources/lang/ files
> 
> A quick fix till you find the issue @lang('RolesREPLACEME'). then you can come back and search and replace

Ok thanks, i've found that too.
