### ISSUE TITLE
INFO : Manual Laravel 8 Update status

### ISSUE THREAD

**Issue by bryanrscott** [rappasoft/laravel-boilerplate#1461]
# Q: Wondering if you can base off this project and manually update to Laravel 8?

A: Not quite yet.   The main blocker at the time of writing is the laravel-nist-password-rules package (Read more here
https://github.com/langleyfoxall/laravel-nist-password-rules/issues/32 ) 

All other packages either have installable versions or have forks which support laravel 8.

**Comment by DivineOmega** [comment]
Hi. This package should now have Laravel 8 support. :+1:
