### ISSUE TITLE
INFO: Manual Laravel 8 Update Status

### ISSUE THREAD

**Issue by bryanrscott** [rappasoft/laravel-boilerplate#1462]
# Q: Wondering if you can base off this project and manually update to Laravel 8?
A: Yes.  But not quite out of box.   A couple of packages have pull requests for laravel 8 compatibility that have not yet been accepted, so you need to reference these development versions specifically in composer.json.

Most packages in composer.json have laravel 8 compatible versions available and published, so upgrading is just following the standard instructions.  But some packages do not yet have a laravel 8 version published, specifically
- Laraguard, and
- invisible-recaptcha

The changes required in composer.json to support these packages under laravel 8 are, firstly add a repositories section as follows.

```
 "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/invisible-recaptcha.git"
        },
        {
            "type": "vcs",
            "url":  "git@github.com:/juanparati/Laraguard.git"
        }
    ],
```

Then in the require section update the versions of the packages as follows:
```
        "albertcht/invisible-recaptcha": "dev-l8-compatibility",
        "darkghosthunter/laraguard": "dev-master",
```

**Comment by rappasoft** [comment]
I'm most likely going to remove these two because I don't feel like waiting, i'll have to come up with some other solution for both

**Comment by rappasoft** [comment]
As of right now the development branch at: efa53eca7673532274d39067ebd79f766116bf35 is good for Laravel 8 - BUT TWO FACTOR AUTH HAS BEEN REMOVED AT THIS POINT

If you do not need 2FA, feed free to use starting at that commit. If you need it, wait until I figure out what to replace it with and make an 8.0 tag.

**Comment by bryanrscott** [comment]
@rappasoft  for laravel 8, have you thought about moving Factories to under app\Domains rather than database\Factories
eg
namespace App\Domains\Announcement\Factories;
namespace App\Domains\Auth\Factories;

**Comment by rappasoft** [comment]
Hmm I don't know. They definitely should be in the factories folder no?

**Comment by bryanrscott** [comment]
Not necessarily now that they are classes.    putting in the domains\???\Factories directory does allow you to more associate with the related domain.     Not a big thing, though

**Comment by rappasoft** [comment]
Laraguard was just updated dev-master so as soon as it's tagged i'll add it back and make a release.
