### ISSUE TITLE
Tailwind

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-boilerplate#1469]
After much deliberation, i've decided to drop Vue, Bootstrap, and CoreUI dependencies in the next major release which i'm currently working on.

The base will be a TALL stack (ish), which will really simplify the frontend workflow.

Currently I still have jQuery installed, because I do think it has its uses, but I also have alpinejs.

You can still easily install Vue if you use it on your projects.

It's still very much in progress, and you can't even use any of the pages yet but you can keep track of the progress and give me suggestions: https://github.com/rappasoft/laravel-boilerplate/compare/feature/tailwind

Looking forward to hearing what everyone thinks. I know this is super opinionated but so is Bootstrap and Vue. Maybe i'll figure something out for the Bootstrap users.

**Comment by rappasoft** [comment]
Old vs. new?

<img width="1792" alt="Screen Shot 2020-11-12 at 11 44 02" src="https://user-images.githubusercontent.com/6026504/98969024-6ae91f80-24dc-11eb-94bf-deba4e1c7414.png">
<img width="1792" alt="Screen Shot 2020-11-12 at 11 43 53" src="https://user-images.githubusercontent.com/6026504/98969032-6d4b7980-24dc-11eb-88f0-bb68dafd5277.png">

**Comment by netwrkx** [comment]
New, looks good.. I hope it comes with all the jetstream goodies

**Comment by rappasoft** [comment]
> New, looks good.. I hope it comes with all the jetstream goodies

I am actually not using Jetstream, it was going to be too big of a transition right now. Plus i'm trying to get away from relying on other pacakges.

The Tailwind transition is big enough. It's going to take a while in itself.

**Comment by redactuk** [comment]
I'm not really a fan of Boostrap. When I do need to use it I generally customise it by stripping out everything I don't need. But I really can't stand Tailwind. How stuffing your markup with endless utility classes was ever seen as a good idea is beyond me. If the new version will be using Tailwind for both frontend and backbend then task of replacing Tailwind each time will no longer make using this boilerplate worth the effort for me so I guess I will need to find a new one.

**Comment by rappasoft** [comment]
A month ago I would have agreed, but then I started actually using it. Bootstrap was great for 10 years, but for me it's time for a change. Tailwind is so much easier to configure and make your own, there's almost no learning curve because its just plain css. Plus you have special tools to extract the utility classes out provided by tailwind, and then blade/Vue components to reuse further. I actually find my workflow faster with Tailwind. Plus the end product ends up looking and responding better, my assets are beyond light, and the sites are lightning fast. With all that being said though, replacing the views from the previous version and just recompiling with Bootstrap and CoreUI should give you back what was there.

**Comment by redactuk** [comment]
Appreciate Tailwind might seem simpler to set up smaller sites more quickly, my issue with  it is more about long-term maintainability and customisation. I find trying to pick though HTML bloated with utility classes a nightmare. To be fair I rarely use Bootstrap either these days and agree it has had its day. Its core layout functionality can easily be achieved now with Grid and Flexbox. Anyway, its your project so entirely your choice what to use. Anyway, your effort and dedication with this boilerplate has been awesome, and was a massive help to me when I first started out with Laravel, so thank you.

**Comment by iosiflivadaru** [comment]
Just found out about Tailwind and it looks amazing, I like it! Can you show us some previews of the backend too?

**Comment by rappasoft** [comment]
I haven't made it very far because I haven't had much time, but the overall look of both sides will be bare bones because i'm expecting everyone to swap it all out for much nicer TailwindUI components, but still be decent enough to where if you didn't want to you could still use it as is.

<img width="1791" alt="Screen Shot 2020-11-18 at 09 27 29" src="https://user-images.githubusercontent.com/6026504/99542673-5398af00-2980-11eb-960d-c54f5708c523.png">
<img width="1792" alt="Screen Shot 2020-11-18 at 09 27 19" src="https://user-images.githubusercontent.com/6026504/99542677-54314580-2980-11eb-9c65-8f242304c8a4.png">
<img width="1792" alt="Screen Shot 2020-11-18 at 09 27 11" src="https://user-images.githubusercontent.com/6026504/99542678-54314580-2980-11eb-9716-8760b22d7e2a.png">

**Comment by surajjdhv** [comment]
Are you going use Laravel Fortify for auth in the upcoming release?

**Comment by rappasoft** [comment]
Right now nothing is changing but the frontend assets.

**Comment by ichuprov** [comment]
any updates on the tailwind version?

**Comment by rappasoft** [comment]
I never ended up making it with this project. I made a pro boilerplate on the TALL stack that I never ended up releasing because it took me so long that I didn't want to release it for free, but got hung up on how much to release it for and just ended up never releasing it. Looks like this though:

<img width="1792" alt="Screen Shot 2022-01-24 at 09 11 23" src="https://user-images.githubusercontent.com/6026504/150798440-507bf35a-7501-4e81-854a-8b125b23811f.png">
<img width="1791" alt="Screen Shot 2022-01-24 at 09 11 08" src="https://user-images.githubusercontent.com/6026504/150798442-d212bb72-9156-4c8a-b481-15c555e468ef.png">
<img width="1792" alt="Screen Shot 2022-01-24 at 09 10 57" src="https://user-images.githubusercontent.com/6026504/150798445-9d344780-4921-48c4-819d-739c13b24c29.png">

**Comment by kasirye** [comment]
Looks great, please release it for educational purposes

**Comment by arunkumar339** [comment]
Hi @rappasoft ,

The tailwind version looks neat! 
I understand your difficulty in releasing. 

Any chance of a private beta? I would love to try it out, 

Thanks
