### ISSUE TITLE
postgresql issue for UTF8

### ISSUE THREAD

**Issue by zachary** [rappasoft/laravel-boilerplate#1474]
SQLSTATE[22021]: Character not in repertoire: 7 ERROR: invalid byte sequence for encoding "UTF8": 0xdf 0xf8 (SQL: insert into "two_factor_authentications" ("authenticatable_id", "authenticatable_type", "digits", "seconds", "window", "algorithm", "recovery_codes", "recovery_codes_generated_at", "safe_devices", "enabled_at", "shared_secret", "label", "updated_at", "created_at") values (1, App\Domains\Auth\Models\User, 6, 30, 1, sha1, ?, ?, ?, ?, ���Vf�G�@���D��;�, admin@admin.com, 2020-11-28 00:50:04, 2020-11-28 00:50:04) returning "id")

please help

**Comment by bryanrscott** [comment]
see https://github.com/rappasoft/laravel-boilerplate/issues/1471
