### ISSUE TITLE
I encountered this error after running npm run dev

### ISSUE THREAD

**Issue by Davidesks** [rappasoft/laravel-boilerplate#1481]
ErrorException
Unable to locate Mix file: /css/backend.css. (View: C:\xampp\htdocs\exampermits\resources\views\backend\layouts\app.blade.php) (View: C:\xampp\htdocs\exampermits\resources\views\backend\layouts\app.blade.php)

  $manifest = $manifests[$manifestPath];

        if (! isset($manifest[$path])) {

            $exception = new Exception("Unable to locate Mix file: {$path}.");

**Comment by rappasoft** [comment]
Did you npm/yarn install first? This is definitely an issue with your project or dev environment.
