### ISSUE TITLE
Missing CORS middleware

### ISSUE THREAD

**Issue by Fitmavincent** [rappasoft/laravel-boilerplate#1499]
# Missing CORS handling:
Come across some CORS handling issue and found the Laravel 8 has already handle this by including the [Laravel-cors](https://github.com/fruitcake/laravel-cors). The boilerplate added the config file, but there's no actual handling. 

# Suggestion:
Laravel 8 included a great CORS handling [HandleCor](https://github.com/laravel/laravel/blob/8.x/app/Http/Kernel.php),
would it be good to add this one in?

**Comment by rappasoft** [comment]
Added in next release thanks.
