### ISSUE TITLE
Failed Jobs table missing UUID column

### ISSUE THREAD

**Issue by PunchRockgroin** [rappasoft/laravel-boilerplate#1501]
Ran into an issue where the failed jobs table is missing the UUID column. See: https://github.com/laravel/laravel/commit/d6eda444a7daf19a0e27861d5e06cb43e71da497 and https://laravel.com/docs/8.x/upgrade#failed-jobs-table-batch-support

In this boilerplate, the migration for failed_jobs at https://github.com/rappasoft/laravel-boilerplate/blob/master/database/migrations/2019_08_19_000000_create_failed_jobs_table.php does not match https://github.com/laravel/laravel/blob/8.x/database/migrations/2019_08_19_000000_create_failed_jobs_table.php#L18

Looks like the QUEUE_FAILED_DRIVER env and config at https://github.com/rappasoft/laravel-boilerplate/blob/master/config/queue.php#L84 is updated to the master and contains "database-uuids" for the default, which described in https://laravel.com/docs/8.x/upgrade#failed-jobs-table-batch-support enables [batch support](https://laravel.com/docs/8.x/queues#job-batching). 

For those already using the boilerplate a migration is required. Otherwise the failed_jobs migration needs to be updated here.

**Comment by rappasoft** [comment]
Fixed in next release. Thanks.
