### ISSUE TITLE
Single Login via Laravel Socialite not working

### ISSUE THREAD

**Issue by the-hardik-sisodia** [rappasoft/laravel-boilerplate#1506]
I have recently found that Single Login works perfectly when we use email id and password to login but when we use socialite and try to login with google, facebook or any other provider this doesn't work. We still have sessions active on more than 1 screen/tab if tried to login via social accounts

**Comment by rappasoft** [comment]
The functionality for that feature uses laravel's logoutOtherDevices() functionality. Not sure how to handle it with social.
