### ISSUE TITLE
Having dependancy issues on php8

### ISSUE THREAD

**Issue by dbrax** [rappasoft/laravel-boilerplate#1512]
tried using laravel-boilerplate on php 8 
Was met with a lot of dependency issues will there be an upgrade on this soon ?

Problem 1
    - langleyfoxall/laravel-nist-password-rules[v4.3.0, ..., v4.4.1] require divineomega/laravel-password-exposed-validation-rule ^2.3.0 -> satisfiable by divineomega/laravel-password-exposed-validation-rule[v2.3.0].
    - langleyfoxall/laravel-nist-password-rules[v4.1.0, ..., v4.1.1] require laravel/framework ^5.4||^6.0 -> found laravel/framework[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^8.24).
    - langleyfoxall/laravel-nist-password-rules v4.2.0 requires laravel/framework ^5.4||^6.0||^7.0 -> found laravel/framework[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.24).
    - divineomega/laravel-password-exposed-validation-rule v2.3.0 requires php ^7.1 -> your php version (8.0.2) does not satisfy that requirement.
    - Root composer.json requires langleyfoxall/laravel-nist-password-rules ^4.1 -> satisfiable by langleyfoxall/laravel-nist-password-rules[v4.1.0, ..., v4.4.1].

 Problem 1
    - Root composer.json requires darkghosthunter/laraguard ^2.0.2 -> satisfiable by darkghosthunter/laraguard[v2.0.2].
    - darkghosthunter/laraguard v2.0.2 requires php ^7.2.15 -> your php version (8.0.2) does not satisfy that requirement.
  Problem 2
    - codedungeon/phpunit-result-printer[0.29.0, ..., 0.29.3] require php ^7.1 -> your php version (8.0.2) does not satisfy that requirement.
    - Root composer.json requires codedungeon/phpunit-result-printer ^0.29 -> satisfiable by codedungeon/phpunit-result-printer[0.29.0, 0.29.1, 0.29.2, 0.29.3].

**Comment by rappasoft** [comment]
These seem to be limitations on packages used, not the boilerplate itself, there's nothing you can do until those packages support PHP 8.

**Comment by dbrax** [comment]
Thanks @rappasoft  i was able to resolve that by some of the package versions strangely composer update was not updating some of the packages had to make changes on composer.json

**Comment by iyeoluwa** [comment]
Can you please some of those changes...I’m also experiencing this issue
