### ISSUE TITLE
default mode to display users 

### ISSUE THREAD

**Issue by awminux** [rappasoft/laravel-boilerplate#1516]
This version uses the livewire table to display users or roles.
How can I use the default mode to display users (like version 5 or 6)? Of course, this library is very powerful, but I do not intend to use livewire table right now.

**Comment by rappasoft** [comment]
You'll have to replace those pages with your own table solution.

**Comment by awminux** [comment]
> You'll have to replace those pages with your own table solution.

I did it but I could not do it properly. Can you install the latest version without livewire table library?

**Comment by rappasoft** [comment]
That package is baked in and runs all the tables, it's not something that can be easily swapped out. Why don't you just keep those run by the package and not use it for any new tables you make.

**Comment by awminux** [comment]
> That package is baked in and runs all the tables, it's not something that can be easily swapped out. Why don't you just keep those run by the package and not use it for any new tables you make.

@rappasoft 

Yes, I can use the default mode for other parts. But my problem is changing the style of the user table or roles. To be more precise, please go to this address and see the style and type of table
 > https://dashlite.net/demo5/components/tables/table-datatable.html

 I added this template to the project but I do not know how to change the user table style to what you saw in the link

**Comment by rappasoft** [comment]
If you have the HTML for that project, you can publish the view files of the package and overwrite them in your own project.
