### ISSUE TITLE
2FA Library Update

### ISSUE THREAD

**Issue by bryanrscott** [rappasoft/laravel-boilerplate#1517]
https://github.com/DarkGhostHunter/Laraguard has released version 3.0.   Most importantly it changes the shared_secret column to text column.  Which makes more compatible with postgresql.

Unfortunately it does have a minimum php level of 7.4 or 8.0.   Happy to do a pull request once this project supports 7.4.

**Comment by rappasoft** [comment]
I'd take a PR for 7.4 and this update, I don't think we'd have to change anything but composer really.

**Comment by rappasoft** [comment]
Nevermind, I just changed it to 7.4, we should all be using at _least_ that anyway.

https://github.com/rappasoft/laravel-boilerplate/commit/d6d16266e87f08ab8d4ebc50164833f841929a32

**Comment by rappasoft** [comment]
I did a manual check and all the tests still pass so I think it's good.
