### ISSUE TITLE
How Create controller and other model Event ... with artisan command 

### ISSUE THREAD

**Issue by faycal1** [rappasoft/laravel-boilerplate#1518]
is it possible to Create controller and other model Event ... with artisan command in a new Domain , thank you

**Comment by rappasoft** [comment]
I'm not sure what you mean. You have access to all the regular Laravel console commands.

**Comment by faycal1** [comment]
Thank you for the answer , what i mean for example if i want to generate a new controller from artisan  in a new domain **Acmy**,  example \App\Domains\Acmy\Http\Controllers\NewController.php , Thank you

**Comment by rappasoft** [comment]
Oh I see. Right now I have no custom generators for that, Laravel's default make command might take a path as an option. I usually just generate in the default directory and then move it manually.

**Comment by faycal1** [comment]
Thank you very much for the Answer , actually is that what i do too :) , i did try with a path but with no success  ,

**Comment by rappasoft** [comment]
If I have time i'll try to think of something in the future.

**Comment by faycal1** [comment]
Thank you
