### ISSUE TITLE
Weird issue with admin user listing

### ISSUE THREAD

**Issue by bryanrscott** [rappasoft/laravel-boilerplate#1522]
I am only reporting this at the moment in case someone else comes across.   Not sure if just my setup (I am running latest versions of all modules)

I was getting weird error on the admin user listing page.  essentially a 500 error.   the correction was to remove the single quote from a comment ie change from

// It's not the person logged in

to 

// It is not the person logged in

in the file https://github.com/rappasoft/laravel-boilerplate/blob/master/resources/views/backend/auth/user/includes/actions.blade.php
on line 58.

Now that is a pretty simple change.  I am just not sure if an issue with my config or boilerplate.

**Comment by rappasoft** [comment]
Hmm that's weird that comment shouldn't make any difference even if it is on the same line.

**Comment by bryanrscott** [comment]
Happy to close nobody else seems to have it.

**Comment by rappasoft** [comment]
Sounds good I'll keep an ear out!
