### ISSUE TITLE
Boilerplate spitting out strange header

### ISSUE THREAD

**Issue by badruayomaya** [rappasoft/laravel-boilerplate#1523]
I recently installed laravel-boilerplate but it is spitting out a strange header (See attached screenshot). Please assist with resolution.
![Boilerplate header](https://user-images.githubusercontent.com/25195157/113903702-2a5eab00-97c9-11eb-86b8-47a6293b00dc.JPG)

**Comment by rappasoft** [comment]
Have never experienced that before or have seen an issue about it. Do you have the project running on a Laravel solution such as Sail, Homestead, or Valet? Or is it running on something like MAMP or XAAMP?

**Comment by badruayomaya** [comment]
Thanks Anthony.

I am using XAAMP. Would it be better to use a Laravel solution?

**Comment by rappasoft** [comment]
It's usually better to use a Laravel solution as they are close to what you will use on production and are built with all the extensions you need.

**Comment by badruayomaya** [comment]
Thank you Anthony.
