### ISSUE TITLE
Failing tests, how to test withFlashSuccess

### ISSUE THREAD

**Issue by leslieharland** [rappasoft/laravel-boilerplate#1532]
When i run php artisan test, all tests are failing,

when i print session, it shows that session('flash-success') is null

**Comment by rappasoft** [comment]
What are you using to run the application and what do you have the session driver set to?

**Comment by leslieharland** [comment]
my session driver is set to array, 
in particular this code gives an error where session is null

`$response->assertSessionHas(['flash_success' => __('alerts.backend.users.updated_password')]);`
