### ISSUE TITLE
Possible to retain menu toggle status across different navigation?

### ISSUE THREAD

**Issue by tangjh** [rappasoft/laravel-boilerplate#1535]
What's a good way to retain the status of menu toggle status when user clicks on different menu links?
Currently regardless of the status, it will go back to fully opened menu once navigate to another page.

**Comment by rappasoft** [comment]
Which menu are you referring to?

**Comment by tangjh** [comment]
The sidebar toggled status to stay the same when navigating from page to page.

**Comment by rappasoft** [comment]
Oh yeah,  I guess it wasn't built into CoreUI. But I would just listen for a click event on that icon and set a cookie and then check for it and apply the hidden class.
