### ISSUE TITLE
label:question Is there a  way to upgrade composer in Boilerplate 7 to use PHP 8 ? 

### ISSUE THREAD

**Issue by fikoulli** [rappasoft/laravel-boilerplate#1537]
Hi All,

PLease, 
Is there a  way to upgrade composer in Boilerplate 7 to use PHP 8 ? 
Thanks for All

**Comment by rappasoft** [comment]
What do you mean? I'm using it with PHP 8 right now you should be able to.

**Comment by fikoulli** [comment]
Hi,
I really appreciate your reply,

Sorry, I didn't specify Boilerplate version, So,

I'm using Boilerplate 7.2.5 with PHP 7.4
and wanted upgrade to PHP 8.0

Is that possible ?

Note :
Before Asking and boring you, I started by updating each package to the 
"Lowest version that accepts PHP8" but without success.

**Comment by rappasoft** [comment]
I guess that would depend on what the errors are, if you set all the packages to the correct versions and specify PHP 8 in composer, as well as you're actually running PHP 8 locally, then there shouldn't be any issues.
