### ISSUE TITLE
Fresh install - everything works but no way to edit an avatar

### ISSUE THREAD

**Issue by shawnfromportland** [rappasoft/laravel-boilerplate#1543]
- I have freshly installed laravel boilerplate
- I can sign into both a superadmin account and regular user account
- 'my account' appears like this:  
<img width="909" alt="08-20-21-13 11 32" src="https://user-images.githubusercontent.com/1243245/130269763-060fe1b6-9adb-43bd-a792-ea4b18366e4b.PNG">
(no ability to edit avatar here)

- 'edit information' appears like this:
<img width="889" alt="08-20-21-13 12 02" src="https://user-images.githubusercontent.com/1243245/130269827-64da97d2-213e-424a-980e-20e35c2649ee.PNG">
(only name and email field, no avatar field to edit). 

- I have run `php artisan storage:link`

I cannot find a solution searching past issues nor the documentation. any help? thanks

**Comment by rappasoft** [comment]
Avatars are gravatar by default: https://github.com/rappasoft/laravel-boilerplate/blob/master/app/Domains/Auth/Models/Traits/Method/UserMethod.php#L102

You can change it to whatever you want.
