### ISSUE TITLE
Getting an error Call to undefined function includeRouteFiles() on fresh install

### ISSUE THREAD

**Issue by newlaravelcoder** [rappasoft/laravel-boilerplate#1545]
Thank you for this awesome package. I am getting this error on routes/web.php

Call to undefined function includeRouteFiles()

How do I get past this?

Thanks!

**Comment by rappasoft** [comment]
That function comes from SystemHelper which is autoloader with HelperServiceProvider. Make sure dump composers autoload and clear all caches.
