### ISSUE TITLE
Language problem for two-step authentication 

### ISSUE THREAD

**Issue by awminux** [rappasoft/laravel-boilerplate#1551]
in disable two-step login, although the user has selected another language, but the errors are displayed in English. 
Is there a solution to this problem?

**Comment by rappasoft** [comment]
This error? https://github.com/rappasoft/laravel-boilerplate/blob/master/app/Domains/Auth/Http/Middleware/TwoFactorAuthenticationStatus.php#L34

**Comment by awminux** [comment]
> This error? https://github.com/rappasoft/laravel-boilerplate/blob/master/app/Domains/Auth/Http/Middleware/TwoFactorAuthenticationStatus.php#L34

No, this error : `The Code is invalid or has expired.`  which is displayed in English only in the Disable two-step authentication form

**Comment by rappasoft** [comment]
That's not me, it's in the Laraguard package. But you should be able to override it: https://github.com/DarkGhostHunter/Laraguard/blob/master/resources/lang/en/validation.php#L4
