### ISSUE TITLE
[JS Console Warning] AlphineJS loaded before Livewire scripts.

### ISSUE THREAD

**Issue by coderkoala** [rappasoft/laravel-boilerplate#1567]
# Before you create an issue make sure that:
[x] Your issue is **strictly related to the boilerplate** itself. Questions about Laravel in general belongs to the [laravel](http://laravel.io/forum) or [laracasts](https://laracasts.com/discuss/) forums.
[x] You have read the [documentation](https://laravel-boilerplate.com) thoroughly.
[x] You have searched for a similar issue among all the former issues (even closed ones).
[x] You have tried to replicate the issue with a clean install of the project.

# Be explicit
![image](https://user-images.githubusercontent.com/30156167/152548207-2c6757a3-41f2-4bda-9c7b-e47de09fa349.png)

I'd like to understand if this is an issue with bootstrapping, or a laravel issue overall. If it's throwing a warning due to bootstrapping, is there any objection as to loading the livewire scripts AFTER the `backend.js` is mixed? 

I'll open a PR, feel free to review and address as necessary.

**Comment by coderkoala** [comment]
It seems the warning's generated in line 44 of `app.blade.php` (main template).

**Comment by rappasoft** [comment]
Bump

**Comment by coderkoala** [comment]
bump
