### ISSUE TITLE
[Question] Automate generation of localization JSON data(__, @lang in template/classes)

### ISSUE THREAD

**Issue by coderkoala** [rappasoft/laravel-boilerplate#1572]
Hi, I'd like to know the best practice for generating localization files for Laravel Boilerplate.

Right now, it's been difficult manually remembering to make the appends to all respective json files, but I'd like to approach the localization with a bit of automation if possible(also include translation APIs to at least have _some_ form of localization until it's addressed). I was wondering how the boilerplate managed that(or you, anthony, personally manage that).

**Comment by hexpit** [comment]
https://github.com/barryvdh/laravel-translation-manager
This package automates your language translation

**Comment by rappasoft** [comment]
No one way is correct. But packages to do it for you are a start. All the language files in this project were community contributed.
