### ISSUE TITLE
Need to update from Laravel 6 BoilerPlate to Laravel 8 or 9

### ISSUE THREAD

**Issue by faisaljawad1** [rappasoft/laravel-boilerplate#1574]
I'm currently looking for a wise solution which can be helpful for me to upgrade from Laravel 6 Boilerplate to Laravel 8 or 9.

![image](https://user-images.githubusercontent.com/99645455/159009463-8caf2c5a-791b-43bc-b565-1d4d14151d76.png)

This is what my current findings are. Is this the only way or someone has found a better solution for this scenario?

**Comment by bryanrscott** [comment]
I have done this a couple times.   Commit by commit is certainly one way to do.

But if you develop your app using app\Domains\, seperate route files for each domain etc in which you seperate your application specific code from the boilerplate framework.   It really comes down to starting a new project and then copying across your app specify files.   

Note the commit by commit way is the only way if you modify the project/laravel files.

Don't forget to also tools like laravel shift / workbench to update your code.
