### ISSUE TITLE
I need to disable 2 step authentication

### ISSUE THREAD

**Issue by hasibkamal** [rappasoft/laravel-boilerplate#1575]
![Screenshot from 2022-03-26 23-09-15](https://user-images.githubusercontent.com/10337913/160250092-06e79c40-cace-4fab-86dc-5f4bc4d1b8e8.png)

I don't want to use this feature.
Any shortcut solution?

**Comment by hexpit** [comment]
set ADMIN_REQUIRES_2FA=false in your .env file
