### ISSUE TITLE
support laravel9?

### ISSUE THREAD

**Issue by jinhuaxiao** [rappasoft/laravel-boilerplate#1584]
# Before you create an issue make sure that:
- Your issue is **strictly related to the boilerplate** itself. Questions about Laravel in general belongs to the [laravel](http://laravel.io/forum) or [laracasts](https://laracasts.com/discuss/) forums.
- You have read the [documentation](https://laravel-boilerplate.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.

# Be explicit
Try to be as explicit as you can when you ask anything.

**Comment by bryanrscott** [comment]
There is a pull request in.   https://github.com/rappasoft/laravel-boilerplate/pull/1583

**Comment by Skintillion** [comment]
Oh awesome!

**Comment by mbnoimi** [comment]
Unfortunately the pull request posted since months ago but no one merged it!!!
Really frustrated.

**Comment by huzzi** [comment]
Please merge this

**Comment by ccsliinc** [comment]
@bryanrscott I have submitted an up to date PR, with Laravel 9, Vite, Livewire Tables 2.

[Boilerplate Update](https://github.com/rappasoft/laravel-boilerplate/pull/1598)
